import React,{useState,useRef,useEffect} from 'react';
import {Modal,SafeAreaView,View,Text,Image,TouchableOpacity,PanResponder,Platform,Alert} from 'react-native';
import {cropGeometry} from './avatarGeometry';
import {exportAvatar} from './avatarExport';
const S=280;
const touchInfo=touches=>touches.length>1?{distance:Math.hypot(touches[0].pageX-touches[1].pageX,touches[0].pageY-touches[1].pageY),angle:Math.atan2(touches[1].pageY-touches[0].pageY,touches[1].pageX-touches[0].pageX)*180/Math.PI}:null;
export default function AvatarCropper({asset,onCancel,onConfirm}){
 const [dimensions,setDimensions]=useState(asset.width&&asset.height?{width:asset.width,height:asset.height}:asset.initialCrop?{width:asset.initialCrop.width,height:asset.initialCrop.height}:null),[position,setPosition]=useState(asset.initialCrop?{zoom:asset.initialCrop.zoom,x:asset.initialCrop.x,y:asset.initialCrop.y,angle:asset.initialCrop.angle||0}:{zoom:1,x:0,y:0,angle:0}),[busy,setBusy]=useState(false);
 const live=useRef(null),start=useRef(null);live.current={position,dimensions};
 useEffect(()=>{if(!dimensions)Image.getSize(asset.uri,(width,height)=>setDimensions({width,height}),()=>Alert.alert('照片无法读取','请重新选择照片'));},[asset.uri]);
 function updatePosition(zoom,x,y,angle){const d=live.current.dimensions;if(!d)return;const crop=cropGeometry(d.width,d.height,zoom,x,y,S,angle);setPosition({zoom:crop.zoom,x:crop.x,y:crop.y,angle:crop.angle});}
 const responder=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>{start.current={...live.current.position,touch:touchInfo(e.nativeEvent.touches||[]),dx:0,dy:0};},onPanResponderMove:(e,g)=>{const info=touchInfo(e.nativeEvent.touches||[]),base=start.current;if(!base)return;if(!!info!==!!base.touch){start.current={...live.current.position,touch:info,dx:g.dx,dy:g.dy};return;}let zoom=base.zoom,angle=base.angle;if(info&&base.touch?.distance){zoom*=info.distance/base.touch.distance;let delta=info.angle-base.touch.angle;if(delta>180)delta-=360;if(delta< -180)delta+=360;angle+=delta;}updatePosition(zoom,base.x+g.dx-base.dx,base.y+g.dy-base.dy,angle);}})).current;
 const rotationStart=useRef(0),rotateResponder=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:()=>{rotationStart.current=live.current.position.angle;},onPanResponderMove:(_,g)=>{const p=live.current.position;updatePosition(p.zoom,p.x,p.y,Math.max(-180,Math.min(180,rotationStart.current+g.dx)));}})).current;
 const crop=dimensions?cropGeometry(dimensions.width,dimensions.height,position.zoom,position.x,position.y,S,position.angle):null;
 async function confirm(){if(!crop||busy)return;setBusy(true);try{await onConfirm({...await exportAvatar(asset.uri,crop),avatarSourceUri:asset.uri,avatarSourceCrop:crop});}catch(e){Alert.alert('头像未保存',e.message);}finally{setBusy(false);}}
 const button=(label,action,disabled=false)=><TouchableOpacity accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={action} style={{paddingHorizontal:18,paddingVertical:14,opacity:disabled?.4:1}}><Text style={{color:'#fff',fontSize:16,fontWeight:'600'}}>{label}</Text></TouchableOpacity>;
 return <Modal visible animationType="slide" onRequestClose={()=>!busy&&onCancel()}><SafeAreaView style={{flex:1,backgroundColor:'#181B1E'}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}>{button('取消',onCancel,busy)}<Text style={{fontSize:17,fontWeight:'600',color:'#fff'}}>调整头像</Text>{button(busy?'处理中':'完成',confirm,!crop||busy)}</View><View style={{flex:1,alignItems:'center',justifyContent:'center',gap:24}}><View testID="avatar-crop-area" {...responder.panHandlers} {...(Platform.OS==='web'?{onWheel:event=>{const p=live.current.position;updatePosition(p.zoom-event.nativeEvent.deltaY*.003,p.x,p.y,p.angle);}}:{})} style={{width:S,height:S,overflow:'hidden',backgroundColor:'#30363B',...(Platform.OS==='web'?{touchAction:'none',cursor:'grab'}:{})}}>{crop&&<Image testID="avatar-crop-image" pointerEvents="none" source={{uri:asset.uri}} resizeMode="stretch" style={{position:'absolute',width:crop.w,height:crop.h,left:crop.left,top:crop.top,transform:[{rotate:`${crop.angle}deg`}]}}/>}<View pointerEvents="none" style={{position:'absolute',left:-S,top:-S,width:S*3,height:S*3,borderRadius:S*1.5,borderWidth:S,borderColor:'rgba(0,0,0,.65)'}}/><View pointerEvents="none" style={{position:'absolute',left:1,top:1,width:S-2,height:S-2,borderRadius:S/2,borderWidth:2,borderColor:'#fff'}}/></View><Text style={{color:'#B7BDC2',fontSize:13}}>拖动照片 · 双指缩放和旋转</Text><View style={{alignItems:'center',gap:8}}><Text style={{color:'#B7BDC2',fontSize:12}}>左右滑动，调整角度</Text><View accessibilityLabel="滑动调整头像角度" testID="avatar-angle-control" {...rotateResponder.panHandlers} style={{width:220,height:44,justifyContent:'center',...(Platform.OS==='web'?{touchAction:'none',cursor:'ew-resize'}:{})}}><View style={{height:2,backgroundColor:'#60676D'}}/><View pointerEvents="none" style={{position:'absolute',left:Math.max(0,Math.min(204,102+position.angle*.55)),width:16,height:16,borderRadius:8,backgroundColor:'#fff'}}/></View></View></View></SafeAreaView></Modal>;
}
