import React,{useState,useRef,useEffect} from 'react';
import {Modal,SafeAreaView,View,Text,Image,TouchableOpacity,PanResponder,Platform,Alert} from 'react-native';
import {cropGeometry} from './avatarGeometry';
import {exportAvatar} from './avatarExport';
const S=280;
export default function AvatarCropper({asset,onCancel,onConfirm}){
 const [dimensions,setDimensions]=useState(asset.width&&asset.height?{width:asset.width,height:asset.height}:null),[position,setPosition]=useState({zoom:1,x:0,y:0}),[busy,setBusy]=useState(false);
 const live=useRef(null),start=useRef(null);live.current={position,dimensions};
 useEffect(()=>{if(!dimensions)Image.getSize(asset.uri,(width,height)=>setDimensions({width,height}),()=>Alert.alert('照片无法读取','请重新选择照片'));},[asset.uri]);
 const responder=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:e=>{const t=e.nativeEvent.touches||[];start.current={...live.current.position,distance:t.length>1?Math.hypot(t[0].pageX-t[1].pageX,t[0].pageY-t[1].pageY):0};},onPanResponderMove:(e,g)=>{const t=e.nativeEvent.touches||[],d=live.current.dimensions;if(!d||!start.current)return;const base=start.current;const zoom=t.length>1&&base.distance?base.zoom*Math.hypot(t[0].pageX-t[1].pageX,t[0].pageY-t[1].pageY)/base.distance:base.zoom;const crop=cropGeometry(d.width,d.height,zoom,base.x+g.dx,base.y+g.dy,S);setPosition({zoom:crop.zoom,x:crop.x,y:crop.y});}})).current;
 const crop=dimensions?cropGeometry(dimensions.width,dimensions.height,position.zoom,position.x,position.y,S):null;
 const zoomBy=amount=>setPosition(p=>{const c=cropGeometry(dimensions.width,dimensions.height,p.zoom+amount,p.x,p.y,S);return {zoom:c.zoom,x:c.x,y:c.y};});
 async function confirm(){if(!crop||busy)return;setBusy(true);try{onConfirm({...await exportAvatar(asset.uri,crop),avatarSourceUri:asset.uri});}catch(e){Alert.alert('头像未保存',e.message);}finally{setBusy(false);}}
 const button=(label,action,disabled=false)=><TouchableOpacity accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={action} style={{paddingHorizontal:18,paddingVertical:14,opacity:disabled?.4:1}}><Text style={{color:'#287ECB',fontSize:16,fontWeight:'600'}}>{label}</Text></TouchableOpacity>;
 return <Modal visible animationType="slide" onRequestClose={()=>!busy&&onCancel()}><SafeAreaView style={{flex:1,backgroundColor:'#fff'}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#EEE'}}>{button('取消',onCancel,busy)}<Text style={{fontSize:17,fontWeight:'600',color:'#292D30'}}>调整头像</Text>{button(busy?'处理中':'完成',confirm,!crop||busy)}</View><View style={{flex:1,alignItems:'center',justifyContent:'center',gap:24}}><Text style={{color:'#8C9593',fontSize:14}}>拖动照片调整位置，双指缩放</Text><View testID="avatar-crop-area" {...responder.panHandlers} style={{width:S,height:S,overflow:'hidden',backgroundColor:'#F3F5F5',borderRadius:8,...(Platform.OS==='web'?{touchAction:'none',cursor:'grab'}:{})}}>{crop&&<Image testID="avatar-crop-image" pointerEvents="none" source={{uri:asset.uri}} resizeMode="stretch" style={{position:'absolute',width:crop.w,height:crop.h,left:crop.left,top:crop.top}}/>}<View pointerEvents="none" style={{position:'absolute',left:0,top:0,width:S,height:S,borderRadius:S/2,borderWidth:1,borderColor:'#fff',backgroundColor:'transparent'}}/></View><View style={{flexDirection:'row',alignItems:'center'}}>{button('缩小',()=>zoomBy(-.25),!crop||position.zoom<=1)}{button('居中',()=>setPosition({zoom:1,x:0,y:0}),!crop)}{button('放大',()=>zoomBy(.25),!crop)}</View>{button('重新选照片',onCancel,busy)}</View></SafeAreaView></Modal>;
}
