import React,{useState} from 'react';
import {View,Text,Image,TouchableOpacity,ScrollView,StyleSheet,Switch,TextInput,Alert,Modal} from 'react-native';
import ChatIcon from './ChatIcon';
export default function ChatInfoScreen({family,onPatch,onBack}){
 const [editor,setEditor]=useState(null),[draft,setDraft]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const settings=family.chatSettings||{},members=family.members||[];
 const unavailable=()=>{setError('此功能尚未接通，当前群聊为本机测试。');Alert.alert('暂未开放','此功能尚未接通，当前群聊为本机测试。')};
 const save=async(update)=>{if(saving)return;setSaving(true);setError('');try{await onPatch(f=>({...f,chatSettings:{...f.chatSettings,...update}}));setEditor(null)}catch{setError('未保存，请重试。')}finally{setSaving(false)}};
 const edit=(key,label,value)=>{setEditor({key,label});setDraft(value||'');setError('')};
 const row=(label,value,action,toggle,indent=false)=><TouchableOpacity key={label} accessibilityRole="button" accessibilityLabel={label} onPress={typeof toggle==='boolean'?undefined:action} disabled={saving} style={[s.row,indent&&s.indent]}><Text style={s.label}>{label}</Text>{typeof toggle==='boolean'?<TouchableOpacity accessibilityRole="switch" accessibilityLabel={label} accessibilityState={{checked:toggle,disabled:saving}} disabled={saving} onPress={action} style={{width:51,height:31,borderRadius:16,backgroundColor:toggle?'#07C160':'#E9E9EB',justifyContent:'center',padding:2}}><View style={{width:27,height:27,borderRadius:14,backgroundColor:'#FFFFFF',alignSelf:toggle?'flex-end':'flex-start'}}/></TouchableOpacity>:<>{value==='__qr__'?<ChatIcon name="qr" size={20} color="#7F7F7F"/>:<Text style={s.value}>{value}</Text>}<View style={s.chevron}><ChatIcon name="forward" size={18} color="#B2B2B2"/></View></>}</TouchableOpacity>;
 return <View style={s.page}><View style={s.header}><TouchableOpacity accessibilityRole="button" accessibilityLabel="返回群聊" style={s.headerButton} onPress={onBack}><ChatIcon name="back" size={24}/></TouchableOpacity><Text style={s.title}>聊天信息 ({members.length})</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="查找聊天内容" style={s.headerButton} onPress={()=>edit('search','查找聊天内容','')}><ChatIcon name="search" size={24}/></TouchableOpacity></View><ScrollView keyboardShouldPersistTaps="handled">
 <View style={s.members}>{members.map(p=><TouchableOpacity key={p.id} style={s.member} onPress={()=>Alert.alert(p.name,'家庭群成员')}><View style={s.avatar}>{p.avatarUri?<Image source={{uri:p.avatarUri}} style={s.image}/>:<Text style={s.initial}>{p.name?.slice(0,1)}</Text>}</View><Text numberOfLines={1} style={s.name}>{p.name}</Text></TouchableOpacity>)}<TouchableOpacity accessibilityRole="button" accessibilityLabel="添加群成员" style={s.member} onPress={unavailable}><View style={[s.avatar,s.add]}><View style={s.plusH}/><View style={s.plusV}/></View></TouchableOpacity></View>
 <View style={s.section}>{row('群聊名称',settings.name||family.name,()=>edit('name','群聊名称',settings.name||family.name))}{row('群二维码','__qr__',unavailable)}{row('群公告',settings.announcement?'已设置':'未设置',()=>edit('announcement','群公告',settings.announcement))}{row('备注',settings.remark,()=>edit('remark','备注',settings.remark))}</View>
 <View style={s.section}>{row('查找聊天内容','',()=>edit('search','查找聊天内容',''))}</View>
 <View style={s.section}>{row('消息免打扰','',()=>save({muted:!settings.muted}),!!settings.muted)}{settings.muted&&row('− 折叠该聊天','',()=>save({folded:!settings.folded}),!!settings.folded,true)}{settings.muted&&<View style={[s.row,s.indent]}><View><Text style={s.label}>− 以下消息仍通知</Text><Text style={s.sub}>@我、@所有人和群公告</Text></View></View>}{row('置顶聊天','',()=>save({pinned:!settings.pinned}),!!settings.pinned)}{row('保存到通讯录','',()=>save({saved:!settings.saved}),!!settings.saved)}</View>
 <View style={s.section}>{row('我在本群的昵称',settings.nickname||'我',()=>edit('nickname','我在本群的昵称',settings.nickname||'我'))}</View>{!!error&&!editor&&<Text accessibilityRole="alert" style={[s.error,{padding:16}]}>{error}</Text>}<Text style={s.hint}>本机测试：消息和设置保存在本机，实时群聊与通知尚未接通。</Text>
 {editor&&<Modal transparent visible onRequestClose={()=>setEditor(null)}><View style={s.overlay}><View style={s.editor}><Text style={s.title}>{editor.label}</Text><TextInput accessibilityLabel={editor.label+'输入'} value={draft} onChangeText={setDraft} style={s.input} placeholder="请输入" multiline/>{editor.key==='search'?<View>{(family.chat||[]).filter(m=>draft.trim()&&m.text?.includes(draft.trim())).map(m=><Text key={m.id} style={s.result}>{m.senderName||m.who||'家人'}：{m.text}</Text>)}{!!draft.trim()&&!(family.chat||[]).some(m=>m.text?.includes(draft.trim()))&&<Text style={s.hint}>没有找到相关消息</Text>}</View>:<TouchableOpacity accessibilityRole="button" accessibilityLabel="保存群设置" disabled={saving||!draft.trim()} onPress={()=>save({[editor.key]:draft.trim()})}><Text style={s.save}>{saving?'保存中…':'保存'}</Text></TouchableOpacity>}<TouchableOpacity onPress={()=>setEditor(null)}><Text style={s.cancel}>关闭</Text></TouchableOpacity>{!!error&&<Text style={s.error}>{error}</Text>}</View></View></Modal>}
 </ScrollView></View>
}
const s=StyleSheet.create({page:{flex:1,width:'100%',maxWidth:480,alignSelf:'center',paddingBottom:72,backgroundColor:'#EDEDED'},header:{height:44,backgroundColor:'#FFFFFF',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:8},headerButton:{width:40,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'600',color:'#191919'},members:{backgroundColor:'#FFFFFF',flexDirection:'row',flexWrap:'wrap',paddingHorizontal:12,paddingTop:14,paddingBottom:24,minHeight:195},member:{width:'16.666%',alignItems:'center',marginBottom:16},avatar:{width:50,height:50,borderRadius:4,backgroundColor:'#D9E5DF',alignItems:'center',justifyContent:'center',overflow:'hidden'},image:{width:50,height:50},initial:{fontSize:18,color:'#527062'},name:{fontSize:13,color:'#888888',marginTop:6,maxWidth:'100%'},add:{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#B2B2B2',borderStyle:'dashed'},plusH:{width:20,height:1,backgroundColor:'#B2B2B2'},plusV:{position:'absolute',height:20,width:1,backgroundColor:'#B2B2B2'},section:{backgroundColor:'#FFFFFF',marginTop:8},row:{minHeight:56,paddingHorizontal:16,paddingVertical:13,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:'#EEEEEE'},label:{fontSize:17,color:'#191919',flex:1},value:{fontSize:17,color:'#888888',maxWidth:'45%'},chevron:{marginLeft:10,width:18,height:24,justifyContent:'center'},indent:{paddingLeft:30},sub:{fontSize:13,color:'#B2B2B2',marginTop:5},hint:{fontSize:11,color:'#999999',padding:16,lineHeight:18},overlay:{flex:1,backgroundColor:'rgba(0,0,0,0.25)',justifyContent:'center',padding:18},editor:{backgroundColor:'#FFFFFF',margin:12,padding:16,borderRadius:8},input:{marginTop:12,borderWidth:1,borderColor:'#DDDDDD',borderRadius:4,padding:10,fontSize:16,minHeight:44},save:{color:'#07C160',fontSize:16,paddingVertical:14,textAlign:'center'},cancel:{color:'#888888',textAlign:'center',padding:10},result:{fontSize:15,lineHeight:24,paddingVertical:8},error:{color:'#B64540',fontSize:12}});
