import React,{useState} from 'react';
import {View,Text,TouchableOpacity,ScrollView,Modal,Image,Switch,StyleSheet} from 'react-native';
import JiaIcon from './JiaIcon';
import {kinshipLabel,branchSharingEnabled} from './familyKinship';

function Avatar({person,size=36}){return <View style={[s.avatar,{width:size,height:size,borderRadius:size/2},person?.dead&&{backgroundColor:'#E4E5E4'}]}>{person?.avatarUri?<Image source={{uri:person.avatarUri}} style={{width:size,height:size,borderRadius:size/2}}/>:<Text style={s.initial}>{(person?.name||'家').slice(-1)}</Text>}</View>}
export function FamilyTreeExtras({family,onSettings}){
 const members=family.members||[];
 const [fromId,setFrom]=useState(()=>members.find(p=>p.id==='me')?.id||members[0]?.id),[toId,setTo]=useState(()=>members.find(p=>p.id!=='me')?.id||members[0]?.id),[choosing,setChoosing]=useState(null);
 const from=members.find(p=>p.id===fromId)||members[0],to=members.find(p=>p.id===toId)||members.find(p=>p.id!==from?.id)||from;
 return <View style={s.extras}>
 <View style={s.card}><View style={s.heading}><JiaIcon name="person" size={21} color="#D99069"/><Text style={s.title}>亲戚怎么称呼</Text></View><Text style={s.hint}>选两位家人，看看彼此的称呼</Text><View style={s.pair}>{[['from',from],['to',to]].map(([key,p],i)=><React.Fragment key={key}>{i===1&&<TouchableOpacity accessibilityLabel="交换两位家人" style={s.swap} onPress={()=>{setFrom(to?.id);setTo(from?.id)}}><Text style={s.swapText}>⇄</Text></TouchableOpacity>}<TouchableOpacity accessibilityLabel={key==='from'?'选择称呼发起人':'选择要称呼的家人'} onPress={()=>setChoosing(key)} style={s.person}><Avatar person={p}/><Text numberOfLines={1} style={s.personName}>{p?.name||'选择家人'}</Text><Text style={s.hint}>⌄</Text></TouchableOpacity></React.Fragment>)}</View><View style={s.result}><Text style={s.hint}>{from?.name||'家人'}称呼{to?.name||'家人'}为</Text><Text style={s.resultText}>{kinshipLabel(members,from?.id,to?.id)}</Text></View></View>
 <View style={s.card}><View style={s.heading}><JiaIcon name="home" size={21} color="#438951"/><Text style={s.title}>家庭分支</Text><TouchableOpacity accessibilityLabel="设置家庭分支可见范围" onPress={onSettings} style={s.settings}><Text style={s.link}>设置 ›</Text></TouchableOpacity></View><Text style={s.hint}>配偶和姻亲的家庭，在这里单独查看</Text><View style={s.branchNote}><JiaIcon name="lock" size={19} color="#87998D"/><View style={{flex:1}}><Text style={s.noteTitle}>{branchSharingEnabled(family)?'允许已确认的家庭关联':'家庭分支已关闭'}</Text><Text style={s.noteCopy}>{branchSharingEnabled(family)?'双方家主确认后，才可查看对方同意公开的基础关系；对方可随时关闭。':'关闭期间，不开放本家庭的分支关系。'}</Text></View></View><Text style={s.footnote}>当前尚未接通跨账号家庭邀请，不会展示其他家庭资料。</Text></View>
 <Modal transparent visible={!!choosing} animationType="slide" onRequestClose={()=>setChoosing(null)}><View style={s.backdrop}><TouchableOpacity accessibilityLabel="取消选择家人" style={{flex:1}} onPress={()=>setChoosing(null)}/><View style={s.sheet}><View style={s.heading}><Text style={s.title}>选择家人</Text><TouchableOpacity accessibilityLabel="关闭家人选择" onPress={()=>setChoosing(null)} style={s.settings}><Text style={s.link}>完成</Text></TouchableOpacity></View><ScrollView style={{maxHeight:350}}>{members.map(p=><TouchableOpacity accessibilityLabel={'选择'+p.name} key={p.id} style={s.choice} onPress={()=>{choosing==='from'?setFrom(p.id):setTo(p.id);setChoosing(null)}}><Avatar person={p}/><Text style={s.personName}>{p.name}</Text><Text style={s.link}>{(choosing==='from'?from?.id:to?.id)===p.id?'✓':''}</Text></TouchableOpacity>)}</ScrollView></View></View></Modal></View>;
}

export function FamilyBranchSettings({family,onSave}){
 const [enabled,setEnabled]=useState(()=>branchSharingEnabled(family)),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function save(){if(saving)return;setSaving(true);setError('');setSaved(false);try{await onSave({...(family.branchSharing||{}),enabled});setSaved(true)}catch(e){setError('保存失败，开关尚未生效，请重试。')}finally{setSaving(false)}}
 return <ScrollView style={s.settingsPage} contentContainerStyle={s.settingsContent}><Text style={s.pageTitle}>家庭设置</Text><Text style={s.hint}>{family.name}</Text><View style={s.card}><Text style={s.title}>家庭分支可见范围</Text><View style={s.switchRow}><View style={{flex:1}}><Text style={s.noteTitle}>允许关联家庭查看</Text><Text style={s.noteCopy}>默认打开，可随时关闭</Text></View><Switch accessibilityLabel="允许关联家庭查看" value={enabled} disabled={saving} onValueChange={v=>{setEnabled(v);setSaved(false);setError('')}} trackColor={{false:'#D9DFDB',true:'#438951'}} thumbColor="#FFFFFF"/></View><Text style={s.noteCopy}>仅限双方已确认关联的家庭，只开放获准公开的基础关系。打开开关不代表向所有人公开。</Text></View><View style={s.card}><Text style={s.noteTitle}>个人内容由本人决定</Text><Text style={s.noteCopy}>照片、故事、生日、住址需要各自授权。私密日记与私人信件不会随家庭分支开放。</Text></View><Text style={s.footnote}>当前保存的是本家庭的开放意愿；跨账号邀请与授权接通前，不会向其他账号开放资料。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}{saved&&<Text accessibilityLiveRegion="polite" style={s.success}>已保存</Text>}<TouchableOpacity accessibilityRole="button" accessibilityLabel="保存家庭分支设置" disabled={saving} onPress={save} style={s.save}><Text style={s.saveText}>{saving?'保存中…':'保存设置'}</Text></TouchableOpacity></ScrollView>;
}
const s=StyleSheet.create({extras:{width:'100%',maxWidth:600,alignSelf:'center',paddingHorizontal:16,paddingTop:4,paddingBottom:100,gap:12},card:{backgroundColor:'#FFFEFC',borderWidth:1,borderColor:'#EAE5DE',borderRadius:20,padding:16},heading:{flexDirection:'row',alignItems:'center',gap:8},title:{fontSize:17,lineHeight:25,fontWeight:'600',color:'#303A3B'},hint:{fontSize:12,lineHeight:20,color:'#939E97'},settings:{marginLeft:'auto',minHeight:40,justifyContent:'center',paddingLeft:10},link:{fontSize:13,color:'#398ACA'},pair:{flexDirection:'row',alignItems:'center',marginTop:12,gap:6},person:{flex:1,minWidth:0,flexDirection:'row',alignItems:'center',gap:7,padding:8,borderWidth:1,borderColor:'#ECEFED',borderRadius:12,backgroundColor:'#FFFFFF'},personName:{flex:1,fontSize:14,color:'#303A3B',fontWeight:'500'},avatar:{alignItems:'center',justifyContent:'center',backgroundColor:'#FFF1DE',overflow:'hidden'},initial:{fontSize:17,color:'#303A3B'},swap:{width:28,minHeight:44,justifyContent:'center',alignItems:'center'},swapText:{fontSize:24,color:'#8A9690'},result:{marginTop:12,padding:12,borderRadius:13,backgroundColor:'#EBF5FD'},resultText:{fontSize:18,lineHeight:27,fontWeight:'600',color:'#398ACA',marginTop:3},branchNote:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:14},noteTitle:{fontSize:14,lineHeight:22,fontWeight:'500',color:'#303A3B'},noteCopy:{fontSize:12,lineHeight:21,color:'#89978D',marginTop:4},footnote:{fontSize:11,lineHeight:19,color:'#919C95',marginTop:4},backdrop:{flex:1,backgroundColor:'rgba(25,35,30,.25)'},sheet:{backgroundColor:'#FFFFFF',borderTopLeftRadius:24,borderTopRightRadius:24,padding:20,paddingBottom:32},choice:{flexDirection:'row',gap:12,alignItems:'center',minHeight:60,borderBottomWidth:1,borderBottomColor:'#F0F1EE'},settingsPage:{flex:1,backgroundColor:'#FAF8F5'},settingsContent:{padding:20,paddingBottom:100,gap:12,maxWidth:600,width:'100%',alignSelf:'center'},pageTitle:{fontSize:26,fontWeight:'700',color:'#303A3B'},switchRow:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:16},save:{minHeight:46,backgroundColor:'#438951',borderRadius:15,alignItems:'center',justifyContent:'center',marginTop:10},saveText:{fontSize:15,fontWeight:'600',color:'#FFFFFF'},error:{fontSize:13,color:'#B85B50',lineHeight:21},success:{fontSize:13,color:'#438951'}});
