import React,{useState} from 'react';
import {View,Text,TextInput,Image,TouchableOpacity,ScrollView,KeyboardAvoidingView,Platform,StyleSheet,Alert} from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import JiaIcon from './JiaIcon';
import {addRelative,mayEditPerson,treeRows,validateParents,validateBirthday} from './familyEditing';

const C={bg:'#FBF4E9',card:'#FFFAF2',brown:'#965331',deep:'#5D321F',muted:'#8F7B6E',line:'#EADBC8'};
export function PersonAvatar({person,uri,size=62}){const source=uri||person?.avatarUri;return <View style={[s.avatar,{width:size,height:size,borderRadius:size/2},person?.dead&&s.deceased]}>{source?<Image source={{uri:source}} style={{width:size,height:size,borderRadius:size/2}} resizeMode="cover"/>:<Text style={[s.initial,{fontSize:size*.36}]}>{(person?.name||'家').slice(-1)}</Text>}</View>}
const Button=({title,onPress,light=false,icon})=><TouchableOpacity onPress={onPress} style={[s.button,light&&s.lightButton]}>{icon&&<JiaIcon name={icon} size={19} color={light?C.brown:'#fff'}/>}<Text style={[s.buttonText,light&&{color:C.brown}]}>{title}</Text></TouchableOpacity>;
const Chips=({options,value,onChange})=><View style={s.chips}>{options.map(([key,label])=><TouchableOpacity key={String(key)} onPress={()=>onChange(key)} style={[s.chip,value===key&&s.chipOn]}><Text style={[s.chipText,value===key&&s.chipOnText]}>{label}</Text></TouchableOpacity>)}</View>;
const Field=({label,value,onChange,placeholder,keyboardType})=><View style={s.field}><Text style={s.label}>{label}</Text><TextInput style={s.input} value={value||''} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={C.muted} keyboardType={keyboardType}/></View>;
function Header({title,onBack}){return <View style={s.header}>{onBack&&<TouchableOpacity onPress={onBack} style={s.back} accessibilityLabel="返回"><JiaIcon name="back"/></TouchableOpacity>}<Text style={s.title}>{title}</Text></View>}
function Editor({children}){return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={s.page}>{children}</ScrollView></KeyboardAvoidingView>}

export function FamilyTreeScreen({family,onPerson,onAdd,focusId='me'}){
 const [mode,setMode]=useState('tree');const members=family.members||[];
 const focus=members.find(p=>p.id===focusId)||members[0];
 const rows=treeRows(members,focus?.id);const width=Math.max(330,...rows.map(r=>r.length*100+32));
 const positions=new Map();rows.forEach((row,ri)=>row.forEach((p,i)=>positions.set(p.id,{x:(width-row.length*100)/2+i*100+50,y:ri*178+24})));
 const edges=[];
 rows.forEach(row=>row.forEach(p=>[p.fatherId,p.motherId].filter(Boolean).forEach(pid=>{const parent=positions.get(pid),child=positions.get(p.id);if(parent&&child&&parent.y<child.y){const top=parent.y+120,bottom=child.y-8,mid=(top+bottom)/2;edges.push(<View key={pid+'-'+p.id} pointerEvents="none"><View style={[s.edge,{left:parent.x-1,top,width:2,height:mid-top}]}/><View style={[s.edge,{left:Math.min(parent.x,child.x),top:mid,width:Math.max(2,Math.abs(child.x-parent.x)),height:2}]}/><View style={[s.edge,{left:child.x-1,top:mid,width:2,height:bottom-mid}]}/></View>);}})));
 const spouseEdges=[];const linked=new Set();for(const p of members){for(const sid of p.spouseIds||[]){const a=positions.get(p.id),b=positions.get(sid),key=[p.id,sid].sort().join('-');if(a&&b&&a.y===b.y&&!linked.has(key)){linked.add(key);const left=Math.min(a.x,b.x)+45;spouseEdges.push(<View key={'spouse'+key} style={{position:'absolute',left,top:a.y+35,width:Math.max(0,Math.abs(a.x-b.x)-90),borderTopWidth:2,borderStyle:'dashed',borderTopColor:'#C8A37E'}}/>);}}}
 return <ScrollView style={s.root} contentContainerStyle={s.page}><View style={s.heading}><View style={s.flex}><Text style={s.title}>家族树</Text><Text style={s.sub}>{family.name} · {members.length} 位家人</Text></View><TouchableOpacity style={s.addSmall} onPress={()=>onAdd(focus)}><JiaIcon name="plus" size={17} color="#fff"/><Text style={s.addText}>添加家人</Text></TouchableOpacity></View><Text style={s.guide}>先点一个人的头像查看资料，再为 TA 添加关系。</Text><Chips options={[["tree","关系图"],["all","全部家人"]]} value={mode} onChange={setMode}/>
 {mode==='tree'?<><Text style={s.sub}>以 {focus?.name||'我'} 为中心，显示相邻三代；更多家人可在“全部家人”中查看。</Text><ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{paddingVertical:10}}><View style={{width,height:rows.length*178+20,backgroundColor:'#F7ECD9',borderRadius:24}}>{edges}{spouseEdges}{rows.map((row,ri)=>row.length?row.map(p=>{const pos=positions.get(p.id);return <TouchableOpacity key={p.id} style={[s.node,{left:pos.x-45,top:pos.y},p.id===focus?.id&&s.nodeFocus]} onPress={()=>onPerson(p)}><PersonAvatar person={p} size={54}/><Text numberOfLines={1} style={s.nodeName}>{p.name}</Text><Text numberOfLines={1} style={s.small}>{p.id===focus?.id?'当前中心':p.relation||'家人'}</Text></TouchableOpacity>}):<View key={'empty'+ri} style={{position:'absolute',top:ri*178+38,left:24,right:24,alignItems:'center'}}><Text style={s.small}>{ri===0?'还未添加父母':'还未添加子女'}</Text><TouchableOpacity onPress={()=>onAdd(focus)} style={s.emptyAdd}><JiaIcon name="plus" size={15}/><Text style={s.link}>添加关系</Text></TouchableOpacity></View>)}</View></ScrollView><Text style={s.small}>实线表示父母与子女关系，虚线表示配偶。头像灰色表示纪念状态。</Text></>:<View style={s.memberGrid}>{members.map(p=><TouchableOpacity key={p.id} style={s.memberCard} onPress={()=>onPerson(p)}><PersonAvatar person={p}/><Text style={s.nodeName}>{p.name}</Text><Text style={s.small}>{p.relation||'家人'}</Text></TouchableOpacity>)}</View>}
 <Button title={`为${focus?.name||'家人'}添加关系`} icon="plus" onPress={()=>onAdd(focus)}/></ScrollView>;
}

export function PersonProfileScreen({person,members,avatarUri,onBack,onEdit,onAdd,onRelation,onFocus,onAvatar,onMemorial}){
 const byId=Object.fromEntries(members.map(p=>[p.id,p]));const editable=mayEditPerson(person);
 const parents=[['父亲',person.fatherId],['母亲',person.motherId]];
 const siblings=members.filter(p=>p.id!==person.id&&((person.fatherId&&p.fatherId===person.fatherId)||(person.motherId&&p.motherId===person.motherId)));
 const children=members.filter(p=>p.fatherId===person.id||p.motherId===person.id);
 return <ScrollView style={s.root} contentContainerStyle={s.page}><Header title="人物档案" onBack={onBack}/><View style={s.profile}><PersonAvatar person={person} uri={avatarUri} size={88}/><Text style={s.profileName}>{person.name}</Text><Text style={s.sub}>{person.id==='me'?'本人':person.isDemo?'示例人物 · 可编辑':person.claimed?'已认领 · 资料由本人维护':'待认领 · 家人代填基础资料'}</Text></View><View style={s.card}><View style={s.heading}><Text style={s.section}>基本信息</Text>{editable&&<TouchableOpacity onPress={onEdit} style={s.editLink}><JiaIcon name="edit" size={16}/><Text style={s.link}>编辑资料</Text></TouchableOpacity>}</View>{[['姓名',person.name],['生日',person.birthday],['住址',person.address]].map(([label,value])=><View key={label} style={s.infoRow}><Text style={s.sub}>{label}</Text><Text style={s.infoValue}>{value||'未填写'}</Text></View>)}{!editable&&<Text style={s.small}>TA 已认领账号，个人资料需要由 TA 本人编辑。</Text>}</View><View style={s.card}><View style={s.heading}><Text style={s.section}>家庭关系</Text><TouchableOpacity onPress={onRelation}><Text style={s.link}>编辑关系</Text></TouchableOpacity></View>{[...parents.map(([label,id])=>[label,byId[id]?.name]),['配偶',(person.spouseIds||[]).map(id=>byId[id]?.name).filter(Boolean).join('、')],['兄弟姐妹',siblings.map(p=>p.name).join('、')],['子女',children.map(p=>p.name).join('、')]].map(([label,value])=><View key={label} style={s.infoRow}><Text style={s.sub}>{label}</Text><Text style={s.infoValue}>{value||'未添加'}</Text></View>)}</View><Button title="添加家庭关系" icon="plus" onPress={onAdd}/><Button title="以 TA 为中心查看家族树" icon="tree" light onPress={onFocus}/>{person.id==='me'&&!person.dead&&<Button title="年度成长头像" light icon="album" onPress={onAvatar}/>} {person.dead&&<Button title="进入纪念页" light icon="memorial" onPress={onMemorial}/>}</ScrollView>;
}

export function PersonEditorScreen({person,onSave,onBack}){
 const [name,setName]=useState(person.name||''),[birthday,setBirthday]=useState(person.birthday||''),[address,setAddress]=useState(person.address||''),[avatarUri,setAvatar]=useState(person.avatarUri||null);
 const editable=mayEditPerson(person),own=person.id==='me';
 async function pickAvatar(){try{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){Alert.alert('需要照片权限','请允许访问照片，再选择头像。');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.85});if(!result.canceled)setAvatar(result.assets[0].uri);}catch{Alert.alert('未能打开相册','请稍后重试。');}}
 function save(){if(!editable)return;if(!name.trim()){Alert.alert('请填写姓名');return;}if(!validateBirthday(birthday.trim())){Alert.alert('请检查生日','请填写真实日期，例如 1990-05-12；暂时不知道可以留空。');return;}onSave({...person,name:name.trim(),birthday:birthday.trim(),address:address.trim(),...(own?{avatarUri}:{} )});}
 return <Editor><Header title="编辑资料" onBack={onBack}/>{own&&<TouchableOpacity onPress={pickAvatar} style={s.profile}><PersonAvatar person={person} uri={avatarUri} size={88}/><Text style={s.link}>选择头像 · 裁成正方形</Text></TouchableOpacity>}<Text style={s.guide}>{own?'填写你自己的基本资料。':'未认领人物只能代填姓名、生日和住址。'}</Text><Field label="姓名" value={name} onChange={setName} placeholder="请输入姓名"/><Field label="生日（可不填）" value={birthday} onChange={setBirthday} placeholder="例如 1990-05-12" keyboardType="numbers-and-punctuation"/><Field label="住址（可不填）" value={address} onChange={setAddress} placeholder="例如 老挝万象"/>{editable?<Button title="保存资料" onPress={save}/>:<Text style={s.guide}>此资料由本人维护。</Text>}</Editor>;
}

export function AddRelativeScreen({anchor,members,onSave,onBack}){
 const [anchorId,setAnchor]=useState(anchor?.id||members[0]?.id),[relation,setRelation]=useState('father'),[mode,setMode]=useState('new'),[existingId,setExisting]=useState(null),[name,setName]=useState(''),[birthday,setBirthday]=useState(''),[address,setAddress]=useState(''),[half,setHalf]=useState(false),[side,setSide]=useState('father');
 const a=members.find(p=>p.id===anchorId);const relations=[['father','父亲'],['mother','母亲'],['spouse','配偶'],['son','儿子'],['daughter','女儿'],['sibling','兄弟姐妹']];
 function save(){try{if(!a)throw new Error('请先选择家人');if(mode==='new'&&!validateBirthday(birthday.trim()))throw new Error('生日格式不正确，请填写 YYYY-MM-DD 或留空');const record=mode==='existing'?members.find(p=>p.id===existingId):{id:`p_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,name:name.trim(),birthday:birthday.trim(),address:address.trim(),claimed:false,dead:false};if(!record)throw new Error('请选择要关联的家人');const next=addRelative(members,a.id,relation,record,{half,parentSide:side});onSave(next,record.id);}catch(e){Alert.alert('暂时不能保存',e.message);}}
 return <Editor><Header title="添加家人" onBack={onBack}/><Text style={s.label}>你要为谁添加关系？</Text><Chips options={members.map(p=>[p.id,p.name])} value={anchorId} onChange={setAnchor}/><Text style={s.label}>TA 是 {a?.name||'这位家人'} 的</Text><Chips options={relations} value={relation} onChange={setRelation}/>{relation==='sibling'&&<View style={s.card}><Text style={s.sub}>默认使用同一组父母，避免重复建人。</Text><Chips options={[[false,'同一组父母'],[true,'同父或同母']]} value={half} onChange={setHalf}/>{half&&<Chips options={[["father","同父"],["mother","同母"]]} value={side} onChange={setSide}/>}</View>}{['son','daughter'].includes(relation)&&<View style={s.card}><Text style={s.label}>{a?.name} 是孩子的</Text><Chips options={[["father","父亲"],["mother","母亲"]]} value={side} onChange={setSide}/><Text style={s.small}>另一位父母可在孩子的“编辑关系”中补充。</Text></View>}<Chips options={[["new","新增人物"],["existing","关联已有家人"]]} value={mode} onChange={setMode}/>{mode==='new'?<><Field label="姓名" value={name} onChange={setName} placeholder="请输入家人的姓名"/><Field label="生日（可不填）" value={birthday} onChange={setBirthday} placeholder="YYYY-MM-DD" keyboardType="numbers-and-punctuation"/><Field label="住址（可不填）" value={address} onChange={setAddress} placeholder="请输入住址"/><Text style={s.small}>新人物为“待认领”。本人认领后，再维护照片与个人经历。</Text></>:<Chips options={members.filter(p=>p.id!==anchorId).map(p=>[p.id,p.name])} value={existingId} onChange={setExisting}/>}<Text style={s.guide}>保存后，{mode==='new'?name||'新人物':members.find(p=>p.id===existingId)?.name||'所选家人'} 将成为 {a?.name} 的{relations.find(r=>r[0]===relation)?.[1]}。</Text><Button title="确认并保存关系" icon="tree" onPress={save}/></Editor>;
}

export function ParentEditorScreen({person,members,onSave,onBack}){
 const [fatherId,setFather]=useState(person.fatherId||null),[motherId,setMother]=useState(person.motherId||null);
 const candidates=members.filter(p=>p.id!==person.id).map(p=>[p.id,p.name]);
 function save(){try{validateParents(members,person.id,fatherId,motherId);onSave({fatherId,motherId});}catch(e){Alert.alert('关系需要调整',e.message);}}
 return <Editor><Header title="编辑家庭关系" onBack={onBack}/><Text style={s.guide}>设置 {person.name} 的父母。兄弟姐妹关系会根据共同父母自动显示。</Text><View style={s.card}><Text style={s.section}>父亲</Text><Chips options={[[null,'暂不填写'],...candidates]} value={fatherId} onChange={setFather}/></View><View style={s.card}><Text style={s.section}>母亲</Text><Chips options={[[null,'暂不填写'],...candidates]} value={motherId} onChange={setMother}/></View><Text style={s.small}>同父异母、同母异父可分别填写；不会自动修改其他人的父母。</Text><Button title="保存家庭关系" onPress={save}/></Editor>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.bg},page:{padding:20,paddingBottom:110},header:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:20},back:{padding:8,marginLeft:-8},title:{fontSize:25,fontWeight:'800',color:C.deep},heading:{flexDirection:'row',alignItems:'center',gap:10,justifyContent:'space-between'},flex:{flex:1},sub:{fontSize:13,color:C.muted,lineHeight:21,marginTop:4},small:{fontSize:11,color:C.muted,lineHeight:18,marginTop:4},guide:{backgroundColor:'#F3E5D2',padding:14,borderRadius:14,color:C.deep,fontSize:13,lineHeight:22,marginVertical:16},addSmall:{flexDirection:'row',alignItems:'center',gap:5,backgroundColor:C.brown,padding:11,borderRadius:18},addText:{color:'#fff',fontSize:12,fontWeight:'700'},avatar:{backgroundColor:'#EAD3B7',alignItems:'center',justifyContent:'center',overflow:'hidden',borderWidth:2,borderColor:'#FFF8ED'},deceased:{opacity:.5,backgroundColor:'#DDD'},initial:{color:C.deep,fontWeight:'600'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginVertical:12},chip:{borderWidth:1,borderColor:C.line,borderRadius:18,paddingHorizontal:14,paddingVertical:10,backgroundColor:C.card},chipOn:{backgroundColor:C.brown,borderColor:C.brown},chipText:{color:C.deep,fontSize:13},chipOnText:{color:'#fff',fontWeight:'700'},button:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,backgroundColor:C.brown,borderRadius:20,padding:16,marginTop:14},lightButton:{backgroundColor:'#F0E0CC'},buttonText:{fontSize:15,color:'#fff',fontWeight:'700'},field:{marginBottom:17},label:{color:C.deep,fontWeight:'600',fontSize:14,marginBottom:7,marginTop:5},input:{backgroundColor:C.card,borderWidth:1,borderColor:C.line,borderRadius:15,padding:15,fontSize:16,color:C.deep},card:{backgroundColor:C.card,borderRadius:20,padding:18,marginVertical:8,borderWidth:1,borderColor:C.line},section:{fontSize:17,fontWeight:'700',color:C.deep},profile:{alignItems:'center',gap:9,paddingVertical:18},profileName:{fontSize:24,fontWeight:'700',color:C.deep},infoRow:{flexDirection:'row',justifyContent:'space-between',gap:20,paddingVertical:11,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:C.line},infoValue:{color:C.deep,fontSize:14,lineHeight:22,flex:1,textAlign:'right'},editLink:{flexDirection:'row',alignItems:'center',gap:5},link:{color:C.brown,fontSize:13,fontWeight:'600'},edge:{position:'absolute',backgroundColor:'#C8A37E'},node:{position:'absolute',width:90,height:120,alignItems:'center',padding:7,borderRadius:17,backgroundColor:C.card,borderWidth:1,borderColor:C.line},nodeFocus:{borderColor:C.brown,borderWidth:2},nodeName:{fontSize:13,fontWeight:'700',color:C.deep,marginTop:6},emptyAdd:{flexDirection:'row',gap:5,alignItems:'center',padding:12},memberGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:16},memberCard:{width:'47%',padding:18,alignItems:'center',borderRadius:20,backgroundColor:C.card,borderWidth:1,borderColor:C.line}});
