import React,{useState} from 'react';
import {View,Text,Image,TouchableOpacity,Modal,StyleSheet,Platform} from 'react-native';
export function memberSummary(person,members=[]){
 const parts=[];if(person.id==='me')parts.push('我');else if(person.relation)parts.push(person.relation);
 if(person.birthday)parts.push(person.birthday.replace(/^(\d{4})-(\d{2})-(\d{2})$/,'$1年$2月$3日'));
 if(person.dead)parts.push('已故');
 const byId=Object.fromEntries(members.map(p=>[p.id,p]));
 for(const id of [person.fatherId,person.motherId])if(byId[id])parts.push(byId[id].name+' · 父母');
 for(const id of person.spouseIds||[])if(byId[id])parts.push(byId[id].name+' · 伴侣');
 const children=members.filter(p=>p.fatherId===person.id||p.motherId===person.id);if(children.length)parts.push(children.map(p=>p.name).join('、')+' · 子女');
 return parts.join(' · ')||'家人';
}
export default function FamilyMemberRow({person,members=[],subtitle,onPress,onDelete,selected}){
 const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const uri=person.avatarUri||person.avatar||person.photo||person.image,crop=person.avatarCrop,size=46,r=crop?size/crop.size:1;
 const selectable=typeof selected==='boolean';
 return <View style={[s.row,selected&&s.selected]}><TouchableOpacity accessibilityRole="button" accessibilityLabel={(selectable?'选择':'查看')+person.name} accessibilityState={selectable?{selected}:undefined} onPress={onPress} style={s.main}><View style={[s.avatar,person.dead&&s.dead]}>{uri?<Image source={{uri}} resizeMode={crop?'stretch':'cover'} style={[crop?{position:'absolute',width:crop.w*r,height:crop.h*r,left:crop.left*r,top:crop.top*r,transform:[{rotate:`${crop.angle||0}deg`}]}:{width:size,height:size},person.dead&&Platform.OS==='web'&&{filter:'grayscale(1)'}]}/>:<Text style={[s.avatarText,person.dead&&{color:'#929B97'}]}>{person.name?.slice(0,1)||'家'}</Text>}</View><View style={s.copy}><Text numberOfLines={1} style={s.name}>{person.name}</Text><Text numberOfLines={1} style={s.meta}>{subtitle||memberSummary(person,members)}</Text></View><Text style={[s.arrow,selected&&{color:'#5089C8'}]}>{selectable?(selected?'✓':'○'):'›'}</Text></TouchableOpacity>{onDelete&&<TouchableOpacity accessibilityRole="button" accessibilityLabel={'删除'+person.name} style={s.remove} onPress={()=>{setError('');setConfirm(true)}}><Text style={s.removeText}>删除</Text></TouchableOpacity>}<Modal transparent visible={confirm} animationType="fade" onRequestClose={()=>{if(!busy)setConfirm(false)}}><View style={s.shade}><View accessibilityViewIsModal style={s.dialog}><Text style={s.dialogTitle}>删除{person.name}？</Text><Text style={s.dialogCopy}>从当前家庭移除人物及其关系，家庭照片会保留。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<View style={s.actions}><TouchableOpacity accessibilityRole="button" disabled={busy} onPress={()=>setConfirm(false)} style={s.action}><Text style={s.cancel}>取消</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" disabled={busy} onPress={async()=>{if(busy)return;setBusy(true);setError('');try{await onDelete(person.id);setConfirm(false)}catch(e){setError(e.message||'删除未成功，请重试')}finally{setBusy(false)}}} style={s.action}><Text style={s.removeText}>{busy?'删除中…':'确认删除'}</Text></TouchableOpacity></View></View></View></Modal></View>;
}
const s=StyleSheet.create({row:{minHeight:76,flexDirection:'row',alignItems:'center',padding:13,borderRadius:20,backgroundColor:'#FFFEFC',borderWidth:1,borderColor:'#EBE5DE',marginBottom:10,shadowColor:'#7F7165',shadowOpacity:.025,shadowRadius:10,shadowOffset:{width:0,height:3}},selected:{backgroundColor:'#F4FAFC',borderColor:'#C6DFEC'},main:{flex:1,flexDirection:'row',alignItems:'center',gap:12,minWidth:0},avatar:{width:46,height:46,borderRadius:23,overflow:'hidden',backgroundColor:'#E8F3F6',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:21,fontWeight:'600',color:'#4489A9'},dead:{backgroundColor:'#E4E4E4'},copy:{flex:1,minWidth:0},name:{fontSize:16,fontWeight:'600',color:'#354246'},meta:{fontSize:12,lineHeight:19,color:'#99A5A3',marginTop:4},arrow:{fontSize:23,color:'#A2B7AA',paddingHorizontal:4},remove:{paddingHorizontal:9,paddingVertical:14,marginLeft:5},removeText:{fontSize:13,color:'#A38F85'},shade:{flex:1,justifyContent:'center',alignItems:'center',padding:24,backgroundColor:'rgba(25,35,30,.32)'},dialog:{width:'100%',maxWidth:340,padding:22,borderRadius:22,backgroundColor:'#FFFFFF'},dialogTitle:{fontSize:19,fontWeight:'600',color:'#354246'},dialogCopy:{fontSize:14,lineHeight:23,color:'#929B97',marginTop:12},actions:{flexDirection:'row',justifyContent:'flex-end',gap:15,marginTop:20},action:{paddingHorizontal:12,paddingVertical:10},cancel:{fontSize:14,color:'#5089C8'},error:{fontSize:13,color:'#B8332B',marginTop:12}});
