import React,{useEffect,useState} from 'react';
import {View,Text,TouchableOpacity,Modal,ScrollView,StyleSheet} from 'react-native';

export function dateString(y,m,d){return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`}
export function calendarCells(y,m){return [...Array(new Date(y,m-1,1).getDay()).fill(null),...Array.from({length:new Date(y,m,0).getDate()},(_,i)=>i+1)]}
export default function FutureDatePicker({visible,value,onConfirm,onClose}){
 const today=new Date(),firstYear=today.getFullYear();
 const [year,setYear]=useState(firstYear),[month,setMonth]=useState(today.getMonth()+1),[draft,setDraft]=useState(''),[choosing,setChoosing]=useState('');
 useEffect(()=>{if(visible){const parts=(value||dateString(firstYear,today.getMonth()+1,today.getDate())).split('-').map(Number);setYear(parts[0]);setMonth(parts[1]);setDraft(value||'');setChoosing('')}},[visible,value]);
 const changeMonth=step=>{const next=new Date(year,month-1+step,1);if(next.getFullYear()<firstYear||next.getFullYear()>firstYear+80)return;setYear(next.getFullYear());setMonth(next.getMonth()+1)};
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.shade}><View style={s.sheet}>
  <View style={s.head}><TouchableOpacity onPress={onClose}><Text style={s.action}>取消</Text></TouchableOpacity><Text style={s.title}>选择日期</Text><TouchableOpacity disabled={!draft} onPress={()=>{onConfirm(draft);onClose()}}><Text style={[s.action,{fontWeight:'600',opacity:draft?1:.3}]}>确定</Text></TouchableOpacity></View>
  <View style={s.navigation}><TouchableOpacity accessibilityLabel="上个月" onPress={()=>changeMonth(-1)} style={s.arrow}><Text style={s.arrowText}>‹</Text></TouchableOpacity><TouchableOpacity onPress={()=>setChoosing(choosing==='year'?'':'year')}><Text style={s.heading}>{year}年 ⌄</Text></TouchableOpacity><TouchableOpacity onPress={()=>setChoosing(choosing==='month'?'':'month')}><Text style={s.heading}>{month}月 ⌄</Text></TouchableOpacity><TouchableOpacity accessibilityLabel="下个月" onPress={()=>changeMonth(1)} style={s.arrow}><Text style={s.arrowText}>›</Text></TouchableOpacity></View>
  <View style={s.calendar}>{choosing?<ScrollView contentContainerStyle={s.options}>{Array.from({length:choosing==='year'?81:12},(_,i)=>choosing==='year'?firstYear+i:i+1).map(n=><TouchableOpacity key={n} style={s.option} onPress={()=>{choosing==='year'?setYear(n):setMonth(n);setChoosing('')}}><Text style={s.dayText}>{n}{choosing==='year'?'年':'月'}</Text></TouchableOpacity>)}</ScrollView>:<><View style={s.week}>{['日','一','二','三','四','五','六'].map(w=><Text key={w} style={s.weekday}>{w}</Text>)}</View><View style={s.days}>{calendarCells(year,month).map((d,i)=>{const date=d?dateString(year,month,d):'',active=date===draft;return <View key={i} style={s.cell}>{d?<TouchableOpacity accessibilityLabel={date} accessibilityState={{selected:active}} onPress={()=>setDraft(date)} style={[s.day,active&&s.selected]}><Text style={[s.dayText,active&&{color:'#fff',fontWeight:'600'}]}>{d}</Text></TouchableOpacity>:null}</View>})}</View></>}</View>
  <View style={s.bottom}><TouchableOpacity onPress={()=>{onConfirm('');onClose()}}><Text style={s.action}>不设置日期</Text></TouchableOpacity><Text style={s.summary}>{draft?`已选 ${draft}`:'请点选一个日期'}</Text></View>
 </View></View></Modal>
}
const s=StyleSheet.create({shade:{flex:1,backgroundColor:'rgba(0,0,0,.25)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:22,borderTopRightRadius:22,paddingHorizontal:18,paddingBottom:28},head:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:18,fontWeight:'600',color:'#242126'},action:{fontSize:16,color:'#242126',paddingVertical:8},navigation:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},heading:{fontSize:18,fontWeight:'600',color:'#242126'},arrow:{paddingHorizontal:12,paddingVertical:5},arrowText:{fontSize:30,color:'#242126'},calendar:{height:300},week:{flexDirection:'row',height:36,alignItems:'center'},weekday:{width:'14.2857%',textAlign:'center',fontSize:13,color:'#8C8790'},days:{flexDirection:'row',flexWrap:'wrap'},cell:{width:'14.2857%',height:43,alignItems:'center',justifyContent:'center'},day:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},selected:{backgroundColor:'#242126'},dayText:{fontSize:17,color:'#242126'},options:{flexDirection:'row',flexWrap:'wrap',paddingBottom:10},option:{width:'25%',height:50,alignItems:'center',justifyContent:'center'},bottom:{height:46,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},summary:{fontSize:14,color:'#8C8790'}});
