import React,{useState} from 'react';
import {View,Text,TextInput,TouchableOpacity,Image,ScrollView,StyleSheet,Alert,Switch,KeyboardAvoidingView,Platform} from 'react-native';
import {useVideoPlayer,VideoView} from 'expo-video';
import {pickImagesAndVideos} from './mediaPicker';
export const theme={bg:'#FBF4E9',card:'#FFFAF2',brown:'#965331',deep:'#5D321F',muted:'#8F7B6E',line:'#EADBC8'};
export const styles=StyleSheet.create({page:{padding:20,paddingBottom:110},title:{fontSize:26,fontWeight:'800',color:theme.deep,marginBottom:8},hint:{fontSize:13,lineHeight:21,color:theme.muted,marginVertical:8},card:{backgroundColor:theme.card,borderWidth:1,borderColor:theme.line,borderRadius:22,padding:18,marginVertical:9},h:{fontSize:17,fontWeight:'700',color:theme.deep},body:{fontSize:15,lineHeight:24,color:theme.deep,marginVertical:8},input:{backgroundColor:'#fff',borderWidth:1,borderColor:theme.line,borderRadius:14,padding:14,color:theme.deep,fontSize:16,marginVertical:8},button:{backgroundColor:theme.brown,padding:15,borderRadius:17,alignItems:'center',marginTop:10},buttonText:{color:'#fff',fontSize:14,fontWeight:'700'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12}});
export function Btn({title,onPress,light=false,disabled=false}){return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.button,light&&{backgroundColor:'#EEE2D3'},disabled&&{opacity:.5}]}><Text style={[styles.buttonText,light&&{color:theme.deep}]}>{title}</Text></TouchableOpacity>}
function Video({uri}){const player=useVideoPlayer(uri);return <VideoView player={player} style={{width:'100%',height:190,borderRadius:14}} nativeControls/>;}
export function MediaPreview({items=[],onRemove}){return <View>{items.map((m,i)=><View key={m.id||i} style={{marginVertical:8}}>{m.type==='video'?<Video uri={m.uri}/>:<Image source={{uri:m.uri}} style={{width:'100%',height:190,borderRadius:14}} resizeMode="cover"/>}{onRemove&&<Btn light title="移除附件" onPress={()=>onRemove(i)}/>}</View>)}</View>}
export async function attachments(){try{const r=await pickImagesAndVideos();if(r.permissionDenied){Alert.alert('需要相册权限');return [];}return r.assets.map((a,i)=>({id:`media_${Date.now()}_${i}`,uri:a.uri,type:a.type||'image'}));}catch(e){Alert.alert('未能打开相册',e.message);return [];}}
export function JournalScreen({title,hint,items=[],onSave,allowMedia=true,life=false}){
 const [editing,setEditing]=useState(null),[text,setText]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[label,setLabel]=useState(''),[media,setMedia]=useState([]),[release,setRelease]=useState(false),[aiFilm,setFilm]=useState(false),[recipients,setRecipients]=useState([]);
 function edit(n){setEditing(n);setText(n.text||'');setDate((n.occurredAt||n.createdAt||'').slice(0,10));setLabel(n.title||'');setMedia(n.media||[]);setRelease(!!n.releaseAfterDeath);setFilm(!!n.aiFilmAllowed);setRecipients(n.recipientIds||[]);}
 function clear(){setEditing(null);setText('');setLabel('');setMedia([]);setRelease(false);setFilm(false);setRecipients([]);}
 function save(){if(!text.trim()&&!media.length){Alert.alert('请写下内容或添加附件');return;}if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date){Alert.alert('请填写有效日期');return;}onSave({...editing,id:editing?.id||`journal_${Date.now()}`,title:label.trim(),text:text.trim(),media,occurredAt:date,createdAt:editing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),authorId:'me',...(life?{releaseAfterDeath:release,aiFilmAllowed:release&&aiFilm,recipientIds:recipients}:{} )});clear();}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.page}><Text style={styles.title}>{title}</Text><Text style={styles.hint}>{hint}</Text><View style={styles.card}><Text style={styles.h}>{editing?'查看 / 编辑记录':'写一条新记录'}</Text>{life&&<TextInput style={styles.input} value={label} onChangeText={setLabel} placeholder="给这段经历起个名字"/>}<TextInput style={styles.input} value={date} onChangeText={setDate} placeholder="发生日期 YYYY-MM-DD"/><TextInput style={[styles.input,{minHeight:140,textAlignVertical:'top'}]} multiline value={text} onChangeText={setText} placeholder="记下发生的事…"/><MediaPreview items={media} onRemove={i=>setMedia(m=>m.filter((_,j)=>i!==j))}/>{allowMedia&&<Btn light title="添加图片 / 视频" onPress={async()=>{const a=await attachments();setMedia(m=>[...m,...a]);}}/>}<Btn title="保存记录" onPress={save}/>{editing&&<Btn light title="关闭这条记录" onPress={clear}/>}</View>{items.map(n=><TouchableOpacity key={n.id} style={styles.card} onPress={()=>edit(n)}><Text style={styles.hint}>{(n.occurredAt||n.createdAt||'').slice(0,10)}</Text><Text style={styles.h}>{n.title||n.text?.slice(0,28)||'图片 / 视频记事'}</Text><Text style={styles.hint}>{n.media?.length?`${n.media.length} 份附件 · `:''}打开查看 / 编辑 ›</Text></TouchableOpacity>)}</ScrollView></KeyboardAvoidingView>;
}
export function ImportantDaysScreen({family,onSave}){
 const [title,setTitle]=useState(''),[date,setDate]=useState('');const birthdays=family.members.filter(p=>p.birthday).map(p=>({id:p.id,title:p.name+'的生日',date:p.birthday}));
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.page}><Text style={styles.title}>重要日子</Text><Text style={styles.hint}>家人的生日与值得记住的纪念日</Text>{[...birthdays,...(family.anniversaries||[])].sort((a,b)=>a.date.slice(5).localeCompare(b.date.slice(5))).map(d=><View key={d.id} style={styles.card}><Text style={styles.h}>{d.title}</Text><Text style={styles.body}>{d.date.slice(5).replace('-','月')}日</Text></View>)}<View style={styles.card}><Text style={styles.h}>添加纪念日</Text><TextInput value={title} onChangeText={setTitle} placeholder="例如：结婚纪念日" style={styles.input}/><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={styles.input}/><Btn title="保存纪念日" onPress={()=>{if(!title.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(date)||isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date){Alert.alert('请填写名称和有效日期');return;}onSave({id:`day_${Date.now()}`,title:title.trim(),date});setTitle('');setDate('');}}/></View></ScrollView>;
}
