import React,{useEffect,useState} from "react";
import {SafeAreaView,View,Text,TouchableOpacity,StyleSheet,ScrollView,TextInput,Alert,Image} from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as ImagePicker from "expo-image-picker";

const C={bg:"#FBF4E9",card:"#FFFAF2",brown:"#965331",deep:"#5D321F",muted:"#8F7B6E",line:"#EADBC8",private:"#F7F0FF"};
const Btn=({children,onPress,secondary})=><TouchableOpacity style={[s.btn,secondary&&s.btn2]} onPress={onPress}><Text style={[s.btnTxt,secondary&&{color:C.deep}]}>{children}</Text></TouchableOpacity>;
const Card=({children,onPress,privateCard})=><TouchableOpacity activeOpacity={onPress?.7:1} onPress={onPress} style={[s.card,privateCard&&{backgroundColor:C.private}]}>{children}</TouchableOpacity>;
const H=({title,back,onBack,right})=><View style={s.header}><TouchableOpacity onPress={onBack}><Text style={s.back}>{back?"‹":""}</Text></TouchableOpacity><Text style={s.hTitle}>{title}</Text><Text style={s.right}>{right||""}</Text></View>;

const initialFamily={id:"f1",name:"张家",member:true,members:[
{id:"p1",name:"爷爷",relation:"爷爷",dead:false},{id:"p2",name:"奶奶",relation:"奶奶",dead:true},
{id:"p3",name:"爸爸",relation:"父亲",dead:false},{id:"p4",name:"妈妈",relation:"母亲",dead:false},
{id:"p5",name:"我",relation:"本人",dead:false},{id:"p6",name:"姐姐",relation:"姐姐",dead:false}]};

export default function App(){
 const [screen,setScreen]=useState("home"),[family,setFamily]=useState(initialFamily),[media,setMedia]=useState([]),[chat,setChat]=useState([{id:1,who:"妈妈",text:"今天晚上一起吃饭吗？"}]),[note,setNote]=useState("");
 const [familyNotes,setFamilyNotes]=useState([]),[selectedPerson,setSelectedPerson]=useState(null),[personName,setPersonName]=useState(""),[personRelation,setPersonRelation]=useState("");
 useEffect(()=>{(async()=>{let x=await AsyncStorage.getItem("jia_state");if(x){let d=JSON.parse(x);setFamily(d.family||initialFamily);setMedia(d.media||[]);setChat(d.chat||chat);setFamilyNotes(d.familyNotes||[])}})()},[]);
 useEffect(()=>{AsyncStorage.setItem("jia_state",JSON.stringify({family,media,chat,familyNotes}))},[family,media,chat,familyNotes]);
 const pick=async(priv=false)=>{let r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images","videos"],allowsMultipleSelection:true,quality:1});if(!r.canceled){let add=r.assets.map((a,i)=>({id:Date.now()+i,uri:a.uri,type:a.type||"image",private:priv,event:"待整理"}));setMedia(v=>[...v,...add]);Alert.alert(priv?"已保存到非公开相册":"已选择照片/视频",priv?"该内容不会进入AI处理。":"正式AI接口后续接入；当前已完成真实本地选择和数据保存。")}};
 const addMember=()=>{if(!personName.trim()||!personRelation.trim()){Alert.alert("请填写完整","请输入姓名和关系");return}
   const p={id:"p"+Date.now(),name:personName.trim(),relation:personRelation.trim(),dead:false};
   setFamily(f=>({...f,members:[...f.members,p]}));setPersonName("");setPersonRelation("");Alert.alert("已添加",p.name+" 已加入当前家庭关系资料。")};
 const saveFamilyNote=()=>{if(!note.trim())return;setFamilyNotes(v=>[{id:Date.now(),text:note.trim(),date:new Date().toLocaleDateString()},...v]);setNote("");Alert.alert("已保存","家庭记事已保存在本机。")};
 const nav=<View style={s.nav}>{[["⌂","首页","home"],["♧","家族","tree"],["＋","","add"],["▧","相册","album"],["●","我的","me"]].map(([i,t,k])=><TouchableOpacity key={k} onPress={()=>setScreen(k)} style={k==="add"?s.plus:s.navItem}><Text style={k==="add"?s.plusT:s.navI}>{i}</Text>{t?<Text style={s.navT}>{t}</Text>:null}</TouchableOpacity>)}</View>;
 const Home=()=> <ScrollView contentContainerStyle={s.page}><View style={s.top}><View><TouchableOpacity onPress={()=>Alert.alert("家庭切换","正式工程已按“一人多个家庭、家庭数据隔离”建模；下一阶段增加第二家庭创建/加入。")}><Text style={s.family}>{family.name}⌄</Text></TouchableOpacity><Text style={s.muted}>{family.members.length}位家人 · {family.member?"家庭会员":"免费家庭"}</Text></View><Text>🔔</Text></View><View style={s.hero}><Text style={s.heroT}>家，是我们一生的牵挂</Text><Text style={s.muted}>把今天，留给未来的家人</Text></View>
 <View style={s.grid}>{[["🌳","家族树","tree"],["🖼️","家庭相册","album"],["💬","家庭群","chat"],["📝","家庭记事","notes"],["🪻","逝者纪念","memorial"],["🔒","私密空间","private"],["📷","老照片修复","restore"],["🎞️","AI回忆影片","film"]].map(x=><TouchableOpacity key={x[1]} style={s.tile} onPress={()=>setScreen(x[2])}><Text style={s.tileI}>{x[0]}</Text><Text>{x[1]}</Text></TouchableOpacity>)}</View>
 <Card><Text style={s.cardTitle}>家人最近上传</Text><Text style={s.muted}>{media.filter(x=>!x.private).length}份家庭照片/视频已保存在本机测试数据中</Text></Card></ScrollView>;
 const Add=()=> <ScrollView contentContainerStyle={s.page}><H title="记录家庭的美好瞬间" back onBack={()=>setScreen("home")}/><Card onPress={()=>pick(false)}><Text style={s.cardTitle}>✨ AI上传照片/视频</Text><Text style={s.muted}>现在可真实选择手机照片/视频；AI识别接口后续对接</Text></Card><Card onPress={()=>pick(false)}><Text style={s.cardTitle}>🖼️ 手动上传照片/视频</Text><Text style={s.muted}>不依赖外部AI，正式可用</Text></Card><Card onPress={()=>setScreen("restore")}><Text style={s.cardTitle}>📷 扫描老照片</Text></Card><Card onPress={()=>setScreen("notes")}><Text style={s.cardTitle}>📝 记录家庭事件</Text></Card></ScrollView>;
 const Album=()=> <ScrollView contentContainerStyle={s.page}><H title="家庭相册"/><Text style={s.tabs}>全部　年份　事件　人物　地点</Text>{media.filter(x=>!x.private).length===0?<Card><Text>还没有家庭照片</Text><Text style={s.muted}>点击中间＋开始上传</Text></Card>:<View style={s.photos}>{media.filter(x=>!x.private).map(x=><Image key={x.id} source={{uri:x.uri}} style={s.photo}/>)}</View>}</ScrollView>;
 const Tree=()=> <ScrollView contentContainerStyle={s.page}><H title={family.name+"家族树"}/><Text style={s.muted}>活着的家人使用彩色头像；逝者灰度并保留纪念标记。</Text>{family.members.map(p=><Card key={p.id} onPress={()=>{setSelectedPerson(p);setScreen("person")}}><View style={s.row}><Text style={[s.avatar,p.dead&&{opacity:.38}]}>👤</Text><View><Text style={s.cardTitle}>{p.name}{p.dead?" 🕯":""}</Text><Text style={s.muted}>{p.relation}</Text></View></View></Card>)}<Btn onPress={()=>setScreen("memberAdd")}>＋ 添加家庭成员</Btn></ScrollView>;
 const MemberAdd=()=> <ScrollView contentContainerStyle={s.page}><H title="添加家庭成员" back onBack={()=>setScreen("tree")}/>
 <Card><Text style={s.cardTitle}>基础信息</Text><TextInput value={personName} onChangeText={setPersonName} placeholder="姓名" style={s.input}/><TextInput value={personRelation} onChangeText={setPersonRelation} placeholder="与我的关系，例如：叔叔" style={[s.input,{marginTop:10}]}/><Text style={s.muted}>未认领人物先保存基础关系资料；本人注册后再认领完善。</Text><Btn onPress={addMember}>保存成员</Btn></Card></ScrollView>;
 const Person=()=>{let p=selectedPerson||family.members[0];return <ScrollView contentContainerStyle={s.page}><H title="人物档案" back onBack={()=>setScreen("tree")}/><View style={{alignItems:"center",marginVertical:15}}><Text style={[s.avatar,{fontSize:70},p.dead&&{opacity:.38}]}>👤</Text><Text style={s.heroT}>{p.name}{p.dead?" 🕯":""}</Text><Text style={s.muted}>{p.relation}</Text></View><Card><Text style={s.cardTitle}>关系资料</Text><Text style={s.muted}>当前家庭：{family.name}</Text><Text style={s.muted}>与我的关系：{p.relation}</Text></Card><Card><Text style={s.cardTitle}>TA的人生时间线</Text><Text style={s.muted}>照片、家庭事件和本人公开记录将在这里按时间关联。</Text></Card><Card onPress={()=>setScreen("album")}><Text style={s.cardTitle}>查看TA相关照片 ›</Text></Card></ScrollView>};
 const Chat=()=> <View style={[s.page,{flex:1}]}><H title={family.name+" · 家庭群"} back onBack={()=>setScreen("home")}/><ScrollView style={{flex:1}}>{chat.map(m=><View key={m.id} style={s.msg}><Text style={s.muted}>{m.who}</Text><Text>{m.text}</Text></View>)}</ScrollView><View style={s.compose}><TextInput value={note} onChangeText={setNote} placeholder="和家人说点什么…" style={s.input}/><TouchableOpacity onPress={()=>{if(note.trim()){setChat(v=>[...v,{id:Date.now(),who:"我",text:note.trim()}]);setNote("")}}}><Text style={s.send}>发送</Text></TouchableOpacity><TouchableOpacity onPress={()=>{pick(false);Alert.alert("家庭照片归档","选择的照片会进入家庭相册；聊天与相册仍保持独立。")}}><Text style={s.send}>＋</Text></TouchableOpacity></View><Text style={s.privacy}>群聊与家庭相册分离；聊天照片是否归档由提供者确认。</Text></View>;
 const Notes=()=> <ScrollView contentContainerStyle={s.page}><H title="家庭记事" back onBack={()=>setScreen("home")}/><Card><Text style={s.cardTitle}>记录今天的家庭故事</Text><TextInput value={note} onChangeText={setNote} multiline placeholder="例如：爸爸今天第一次学会用智能手机…" style={[s.input,{height:130,textAlignVertical:"top"}]}/><Btn onPress={saveFamilyNote}>保存家庭记事</Btn></Card>{familyNotes.map(n=><Card key={n.id}><Text style={s.muted}>{n.date}</Text><Text style={{fontSize:16,lineHeight:24,marginTop:5}}>{n.text}</Text></Card>)}</ScrollView>;
 const Private=()=> <ScrollView contentContainerStyle={[s.page,{backgroundColor:C.private}]}><H title="🔒 私密空间" back onBack={()=>setScreen("home")}/><Text style={s.centerMuted}>这里只属于你一个人 · 永久不进入AI分析</Text><Card privateCard onPress={()=>pick(true)}><Text style={s.cardTitle}>🔐 非公开相册</Text><Text style={s.muted}>独立手动上传 · 家主和AI均不可访问</Text></Card><Card privateCard><Text style={s.cardTitle}>📓 个人记事本</Text></Card><Card privateCard><Text style={s.cardTitle}>🪻 想念TA</Text><Text style={s.muted}>未来支持指定时间/指定传承人解锁</Text></Card><View style={s.photos}>{media.filter(x=>x.private).map(x=><Image key={x.id} source={{uri:x.uri}} style={s.photo}/>)}</View></ScrollView>;
 const Placeholder=({title,text})=><ScrollView contentContainerStyle={s.page}><H title={title} back onBack={()=>setScreen("home")}/><View style={s.hero}><Text style={s.heroT}>{title}</Text><Text style={s.muted}>{text}</Text></View><Card><Text style={s.cardTitle}>正式工程接口已预留</Text><Text style={s.muted}>该能力依赖第三方服务，按你的要求暂不绑定供应商。</Text></Card></ScrollView>;
 const Me=()=> <ScrollView contentContainerStyle={s.page}><H title="我的"/><Card><Text style={s.cardTitle}>👤 张小明</Text><Text style={s.muted}>个人与家庭设置</Text></Card><Card onPress={()=>setScreen("private")}><Text>🔒 私密空间</Text></Card><Card><Text>🏠 我的家庭 · {family.name}</Text></Card><Card><Text>⚙️ 设置 / 数据导出 / 账号注销</Text></Card></ScrollView>;
 let body=screen==="home"?<Home/>:screen==="add"?<Add/>:screen==="album"?<Album/>:screen==="tree"?<Tree/>:screen==="chat"?<Chat/>:screen==="notes"?<Notes/>:screen==="memberAdd"?<MemberAdd/>:screen==="person"?<Person/>:screen==="private"?<Private/>:screen==="restore"?<Placeholder title="老照片扫描修复" text="原图永久保留；修复版作为衍生版本。真实修复API后续对接。"/>:screen==="film"?<Placeholder title="AI回忆影片" text="影片生成服务后续对接，家庭记忆数据结构已经独立。"/>:screen==="memorial"?<Placeholder title="逝者纪念" text="逝者仍保留在家族关系、相册和人生时间线中。"/>:<Home/>;
 return <SafeAreaView style={s.app}>{body}{!["chat"].includes(screen)&&nav}</SafeAreaView>
}
const s=StyleSheet.create({
app:{flex:1,backgroundColor:C.bg},page:{padding:18,paddingBottom:105,backgroundColor:C.bg,minHeight:"100%"},header:{height:52,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:34,color:C.deep,width:45},hTitle:{fontSize:20,fontWeight:"700",color:C.deep},right:{width:45},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:16},family:{fontSize:21,fontWeight:"800",color:C.deep},muted:{color:C.muted,fontSize:13,marginTop:4,lineHeight:20},hero:{backgroundColor:"#F8E1C4",borderRadius:24,padding:22,marginVertical:12},heroT:{fontSize:22,fontWeight:"800",color:C.deep,marginBottom:7},grid:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between"},tile:{width:"23%",alignItems:"center",marginVertical:12},tileI:{width:56,height:56,textAlign:"center",paddingTop:13,fontSize:26,backgroundColor:"#F5DFC3",borderRadius:18,overflow:"hidden",marginBottom:6},card:{backgroundColor:C.card,borderColor:"#F0E4D4",borderWidth:1,borderRadius:20,padding:16,marginVertical:7},cardTitle:{fontSize:17,fontWeight:"750",color:C.deep},row:{flexDirection:"row",alignItems:"center",gap:12},avatar:{fontSize:36},tabs:{backgroundColor:"#F3E8D8",padding:11,borderRadius:18,color:C.deep,marginBottom:12},photos:{flexDirection:"row",flexWrap:"wrap",gap:4},photo:{width:"32%",aspectRatio:1,borderRadius:8,backgroundColor:"#ddd"},nav:{position:"absolute",bottom:0,left:0,right:0,height:82,backgroundColor:"#FFFAF3",borderTopWidth:1,borderColor:C.line,flexDirection:"row",alignItems:"center",justifyContent:"space-around"},navItem:{alignItems:"center",width:62},navI:{fontSize:23,color:C.deep},navT:{fontSize:11,color:C.muted},plus:{width:58,height:58,borderRadius:29,backgroundColor:C.brown,alignItems:"center",justifyContent:"center"},plusT:{fontSize:35,color:"#fff"},btn:{backgroundColor:C.brown,borderRadius:16,padding:15,alignItems:"center",marginTop:12},btn2:{backgroundColor:"#F3E5D3"},btnTxt:{color:"#fff",fontSize:16,fontWeight:"700"},msg:{alignSelf:"flex-start",maxWidth:"82%",backgroundColor:"#FFF9F0",padding:12,borderRadius:15,marginVertical:6},compose:{flexDirection:"row",gap:8,alignItems:"center"},input:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:C.line,borderRadius:14,padding:13,fontSize:16},send:{backgroundColor:C.brown,color:"#fff",paddingHorizontal:15,paddingVertical:12,borderRadius:14,overflow:"hidden"},privacy:{fontSize:11,color:C.muted,textAlign:"center",paddingVertical:8},centerMuted:{textAlign:"center",color:C.muted,marginBottom:10}
});