import React, {useMemo, useState} from 'react';
import {View, Text, Image, ScrollView, TouchableOpacity, StyleSheet} from 'react-native';
import JiaIcon from './JiaIcon';
import {PersonAvatar} from './FamilyPeopleScreens';

const C={bg:'#FBF4E9',card:'#FFFAF2',brown:'#965331',deep:'#5D321F',muted:'#8F7B6E',line:'#EADBC8'};
export function groupMemories(media, members, tab){
 if(tab==='all')return [{key:'all',title:'所有家庭记忆',items:media}];
 if(tab==='people')return [...members.map(p=>({key:p.id,title:p.name,items:media.filter(m=>(m.personIds||[]).includes(p.id))})),{key:'untagged',title:'待确认人物',items:media.filter(m=>!(m.personIds||[]).length)}].filter(g=>g.items.length);
 const groups=new Map();
 for(const m of media){
  const date=String(m.takenAt||m.createdAt||'');
  const year=/^\d{4}/.test(date)?date.slice(0,4):'日期待补充';
  const value=tab==='years'?year:tab==='events'?(m.event||'未分类'):(m.locationName||m.location?.name||(typeof m.location==='string'?m.location:null)||'地点待补充');
  if(!groups.has(value))groups.set(value,[]);
  groups.get(value).push(m);
 }
 return Array.from(groups,([key,items])=>({key,title:tab==='years'&&/^\d{4}$/.test(key)?key+'年':key,items})).sort((a,b)=>tab==='years'?(a.key==='日期待补充'?1:b.key==='日期待补充'?-1:b.key.localeCompare(a.key)):0);
}
function Thumb({item,style}){return item.type==='video'?<View style={[style,s.video]}><JiaIcon name="film" size={28}/><Text style={s.videoLabel}>视频</Text></View>:item.uri?<Image source={{uri:item.uri}} style={style} resizeMode="cover"/>:<View style={[style,s.video]}><JiaIcon name="album" size={28}/></View>}
export function MemoryAlbumScreen({family,onMedia,onAdd}){
 const [tab,setTab]=useState('all');
 const media=(family.media||[]).filter(m=>m.albumArchived!==false&&!m.private);
 const groups=useMemo(()=>groupMemories(media,family.members||[],tab),[family.media,family.members,tab]);
 return <ScrollView style={s.scroll} contentContainerStyle={s.page}>
  <View style={s.heading}><View><Text style={s.title}>家庭相册</Text><Text style={s.sub}>{family.name} · {media.length} 份家庭记忆</Text></View><TouchableOpacity onPress={onAdd} style={s.add} accessibilityLabel="上传家庭照片"><JiaIcon name="plus" color="#fff" size={24}/></TouchableOpacity></View>
  <View style={s.tabs}>{[['all','全部'],['years','年份'],['events','事件'],['people','人物'],['places','地点']].map(([key,label])=><TouchableOpacity key={key} onPress={()=>setTab(key)} style={[s.tab,tab===key&&s.tabOn]} accessibilityRole="tab" accessibilityState={{selected:tab===key}}><Text style={[s.tabText,tab===key&&s.tabOnText]}>{label}</Text></TouchableOpacity>)}</View>
  {!media.length?<View style={s.empty}><View style={s.emptyIcon}><JiaIcon name="album" size={36}/></View><Text style={s.emptyTitle}>把第一张合照留在这里</Text><Text style={s.emptyText}>全家福、旅行、生日，都是值得珍藏的记忆。</Text><TouchableOpacity style={s.button} onPress={onAdd}><Text style={s.buttonText}>上传照片 / 视频</Text></TouchableOpacity></View>:groups.map(g=><View key={g.key} style={s.group}><View style={s.groupHead}><Text style={s.groupTitle}>{g.title}</Text><Text style={s.sub}>{g.items.length} 份</Text></View><View style={s.grid}>{g.items.map(m=><TouchableOpacity key={m.id} style={s.cell} onPress={()=>onMedia(m)} accessibilityLabel={m.fileName||'查看家庭照片'}><Thumb item={m} style={s.photo}/><View style={s.caption}><Text numberOfLines={1} style={s.photoLabel}>{m.event&&m.event!=='未分类'?m.event:(m.type==='video'?'家庭视频':'家庭照片')}</Text><Text style={s.small}>{m.peopleConfirmed?'人物已确认':'确认照片里有谁 ›'}</Text></View></TouchableOpacity>)}</View></View>)}
 </ScrollView>;
}
export function MyHomeScreen({family,onPerson,onGo}){
 const me=(family.members||[]).find(p=>p.id==='me');
 const rows=[['home','我的家庭',family.name,'families'],['album','家庭相册',`${(family.media||[]).filter(m=>m.albumArchived!==false&&!m.private).length} 份记忆`,'album'],['notes','家庭记事','记录家人的故事','notes'],['chat','家信 / 家讯','和家人说说话','chat'],['lock','私密空间','个人相册、日记与思念','private']];
 return <ScrollView style={s.scroll} contentContainerStyle={s.page}><Text style={s.title}>我的</Text><TouchableOpacity style={s.profile} onPress={()=>me&&onPerson(me)}><PersonAvatar person={me} size={60}/><View style={s.flex}><Text style={s.name}>{me?.name||'我'}</Text><Text style={s.sub}>查看个人档案</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity><View style={s.rows}>{rows.map(([icon,title,hint,key])=><TouchableOpacity key={key} onPress={()=>onGo(key)} style={s.row}><View style={s.rowIcon}><JiaIcon name={icon} size={21}/></View><View style={s.flex}><Text style={s.rowTitle}>{title}</Text><Text style={s.small}>{hint}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</View><Text style={s.footer}>把家人的故事，留给未来</Text></ScrollView>;
}
const s=StyleSheet.create({scroll:{flex:1,backgroundColor:C.bg},page:{paddingHorizontal:20,paddingTop:22,paddingBottom:105},heading:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:25,fontWeight:'800',color:C.deep},sub:{fontSize:12,lineHeight:19,color:C.muted,marginTop:4},add:{width:40,height:40,borderRadius:20,backgroundColor:C.brown,alignItems:'center',justifyContent:'center'},addText:{fontSize:27,color:'#fff'},tabs:{flexDirection:'row',backgroundColor:'#F3E6D4',borderRadius:20,padding:4,marginVertical:20},tab:{flex:1,paddingVertical:9,borderRadius:17,alignItems:'center'},tabOn:{backgroundColor:C.brown},tabText:{fontSize:12,color:C.deep},tabOnText:{color:'#fff',fontWeight:'700'},group:{marginBottom:22},groupHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:10},groupTitle:{fontSize:17,fontWeight:'700',color:C.deep},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},cell:{width:'48%',backgroundColor:C.card,borderRadius:15,overflow:'hidden'},photo:{width:'100%',aspectRatio:1,backgroundColor:'#EADBC8'},video:{alignItems:'center',justifyContent:'center',backgroundColor:'#D8BDA1'},play:{fontSize:28,color:C.deep},videoLabel:{color:C.deep,fontSize:12,marginTop:6},caption:{padding:10},photoLabel:{fontSize:13,fontWeight:'600',color:C.deep},small:{fontSize:11,color:C.muted,lineHeight:18,marginTop:3},empty:{alignItems:'center',paddingVertical:42,paddingHorizontal:14},emptyIcon:{width:80,height:80,borderRadius:24,backgroundColor:'#F3E6D4',alignItems:'center',justifyContent:'center'},emptySymbol:{fontSize:38,color:C.brown},emptyTitle:{fontSize:19,color:C.deep,fontWeight:'700',marginTop:20},emptyText:{fontSize:13,color:C.muted,lineHeight:23,textAlign:'center',marginTop:10},button:{backgroundColor:C.brown,borderRadius:22,paddingVertical:14,paddingHorizontal:30,marginTop:24},buttonText:{fontWeight:'700',color:'#fff'},profile:{flexDirection:'row',alignItems:'center',gap:14,padding:20,backgroundColor:'#F5E6D2',borderRadius:22,marginVertical:22},avatar:{height:60,width:60,borderRadius:30,backgroundColor:'#D9B28B',alignItems:'center',justifyContent:'center'},avatarText:{fontSize:26,color:C.deep},name:{fontSize:20,fontWeight:'700',color:C.deep},flex:{flex:1},arrow:{fontSize:24,color:C.brown},rows:{borderRadius:20,backgroundColor:C.card,paddingHorizontal:15},row:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:16,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:C.line},rowIcon:{width:35,height:35,borderRadius:11,backgroundColor:'#F5E7D5',alignItems:'center',justifyContent:'center'},rowSymbol:{fontSize:20,color:C.brown},rowTitle:{fontSize:15,fontWeight:'600',color:C.deep},footer:{textAlign:'center',color:C.muted,fontSize:12,marginTop:28}});
