import React,{useRef,useState} from "react";
import {View,Text,TouchableOpacity,StyleSheet,Alert,Image} from "react-native";
import {CameraView,useCameraPermissions} from "expo-camera";
import JiaIcon from "./JiaIcon";
const C={bg:"#171411",brown:"#965331",cream:"#FFF8EF",muted:"#CBBEB3"};
export default function OldPhotoScanner({onBack,onSave}){
 const camera=useRef(null),[permission,requestPermission]=useCameraPermissions(),[shot,setShot]=useState(null),[busy,setBusy]=useState(false);
 async function take(){if(!camera.current||busy)return;try{setBusy(true);const r=await camera.current.takePictureAsync({quality:.92,skipProcessing:false});if(r?.uri)setShot(r);}catch(e){Alert.alert("拍摄失败","请重新拍摄。");}finally{setBusy(false)}}
 if(!permission)return <View style={s.center}><Text style={s.white}>正在检查相机权限…</Text></View>;
 if(!permission.granted)return <View style={s.center}><JiaIcon name="scan" size={48} color={C.cream}/><Text style={s.title}>需要使用相机</Text><Text style={s.hint}>扫描纸质老照片需要相机权限。</Text><TouchableOpacity style={s.main} onPress={requestPermission}><Text style={s.mainText}>允许使用相机</Text></TouchableOpacity><TouchableOpacity onPress={onBack}><Text style={s.cancel}>返回</Text></TouchableOpacity></View>;
 if(shot)return <View style={s.root}><Image source={{uri:shot.uri}} style={s.preview} resizeMode="contain"/><View style={s.review}><TouchableOpacity style={s.secondary} onPress={()=>setShot(null)}><Text style={s.secondaryText}>重新拍摄</Text></TouchableOpacity><TouchableOpacity style={s.mainSmall} onPress={()=>onSave?.(shot)}><Text style={s.mainText}>使用照片</Text></TouchableOpacity></View></View>;
 return <View style={s.root}><CameraView ref={camera} style={StyleSheet.absoluteFill} facing="back"/><View style={s.top}><TouchableOpacity onPress={onBack} style={s.circle}><JiaIcon name="back" size={22} color="#fff"/></TouchableOpacity><Text style={s.topTitle}>扫描老照片</Text><View style={{width:42}}/></View><View style={s.guide}><View style={s.cornerTL}/><View style={s.cornerTR}/><View style={s.cornerBL}/><View style={s.cornerBR}/><Text style={s.guideText}>将老照片完整放入框内</Text></View><View style={s.bottom}><Text style={s.tip}>保持平稳，避免反光</Text><TouchableOpacity disabled={busy} onPress={take} style={s.shutter}><View style={s.shutterIn}/></TouchableOpacity></View></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#000"},center:{flex:1,backgroundColor:C.bg,alignItems:"center",justifyContent:"center",padding:28},white:{color:"#fff"},title:{fontSize:24,fontWeight:"800",color:C.cream,marginTop:18},hint:{fontSize:14,color:C.muted,textAlign:"center",marginTop:10,lineHeight:22},main:{marginTop:28,backgroundColor:C.brown,borderRadius:20,paddingVertical:14,paddingHorizontal:28},mainSmall:{backgroundColor:C.brown,borderRadius:20,paddingVertical:14,paddingHorizontal:28},mainText:{color:"#fff",fontWeight:"700"},cancel:{color:C.muted,marginTop:22},top:{position:"absolute",top:18,left:18,right:18,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},circle:{width:42,height:42,borderRadius:21,backgroundColor:"rgba(0,0,0,.45)",alignItems:"center",justifyContent:"center"},topTitle:{color:"#fff",fontSize:17,fontWeight:"700"},guide:{position:"absolute",left:28,right:28,top:"22%",height:"48%",justifyContent:"flex-end",alignItems:"center"},guideText:{color:"#fff",backgroundColor:"rgba(0,0,0,.45)",paddingHorizontal:12,paddingVertical:7,borderRadius:14,marginBottom:10},cornerTL:{position:"absolute",left:0,top:0,width:42,height:42,borderLeftWidth:3,borderTopWidth:3,borderColor:"#fff"},cornerTR:{position:"absolute",right:0,top:0,width:42,height:42,borderRightWidth:3,borderTopWidth:3,borderColor:"#fff"},cornerBL:{position:"absolute",left:0,bottom:0,width:42,height:42,borderLeftWidth:3,borderBottomWidth:3,borderColor:"#fff"},cornerBR:{position:"absolute",right:0,bottom:0,width:42,height:42,borderRightWidth:3,borderBottomWidth:3,borderColor:"#fff"},bottom:{position:"absolute",left:0,right:0,bottom:34,alignItems:"center"},tip:{color:"#fff",fontSize:12,marginBottom:15},shutter:{width:76,height:76,borderRadius:38,borderWidth:4,borderColor:"#fff",alignItems:"center",justifyContent:"center"},shutterIn:{width:60,height:60,borderRadius:30,backgroundColor:"#fff"},preview:{flex:1,width:"100%",backgroundColor:"#000"},review:{position:"absolute",bottom:32,left:20,right:20,flexDirection:"row",justifyContent:"space-between",gap:12},secondary:{flex:1,backgroundColor:"#fff",borderRadius:20,paddingVertical:14,alignItems:"center"},secondaryText:{color:"#4F3428",fontWeight:"700"},mainSmall:{flex:1,backgroundColor:C.brown,borderRadius:20,paddingVertical:14,alignItems:"center"}});
