import React,{useState} from "react";
import {View,Text,TouchableOpacity,StyleSheet,Alert,Image} from "react-native";
import * as ImagePicker from "expo-image-picker";
import JiaIcon from "./JiaIcon";
const C={bg:"#171411",brown:"#965331",cream:"#FFF8EF",muted:"#CBBEB3"};
export default function OldPhotoScanner({onBack,onSave}){
 const [shot,setShot]=useState(null),[busy,setBusy]=useState(false);
 async function take(){if(busy)return;try{setBusy(true);const perm=await ImagePicker.requestCameraPermissionsAsync();if(!perm.granted){Alert.alert("需要相机权限","扫描纸质老照片需要允许使用相机。");return}const r=await ImagePicker.launchCameraAsync({mediaTypes:["images"],quality:.92,allowsEditing:false});if(!r.canceled&&r.assets?.[0])setShot(r.assets[0]);}catch(e){Alert.alert("无法打开相机","请检查相机权限后重试。");}finally{setBusy(false)}}
 if(shot)return <View style={s.root}><Image source={{uri:shot.uri}} style={s.preview} resizeMode="contain"/><View style={s.review}><TouchableOpacity style={s.secondary} onPress={()=>setShot(null)}><Text style={s.secondaryText}>重新拍摄</Text></TouchableOpacity><TouchableOpacity style={s.mainSmall} onPress={()=>onSave?.(shot)}><Text style={s.mainText}>使用照片</Text></TouchableOpacity></View></View>;
 return <View style={s.center}><TouchableOpacity onPress={onBack} style={s.back}><Text style={s.cancel}>‹ 返回</Text></TouchableOpacity><View style={s.frame}><JiaIcon name="scan" size={52} color={C.cream}/><Text style={s.frameTitle}>扫描老照片</Text><Text style={s.hint}>拍摄时将老照片完整放入画面，保持平稳并避免反光。</Text></View><TouchableOpacity disabled={busy} style={s.main} onPress={take}><Text style={s.mainText}>{busy?"正在打开相机…":"打开相机扫描"}</Text></TouchableOpacity></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#000"},center:{flex:1,backgroundColor:C.bg,alignItems:"center",justifyContent:"center",padding:26},back:{position:"absolute",top:24,left:22},cancel:{color:C.cream,fontSize:15},frame:{width:"100%",aspectRatio:.78,borderWidth:2,borderColor:"#EADFD5",borderRadius:26,alignItems:"center",justifyContent:"center",padding:30},frameTitle:{fontSize:24,fontWeight:"800",color:C.cream,marginTop:18},hint:{fontSize:14,color:C.muted,textAlign:"center",marginTop:10,lineHeight:22},main:{marginTop:24,backgroundColor:C.brown,borderRadius:20,paddingVertical:15,paddingHorizontal:34},mainText:{color:"#fff",fontWeight:"700"},preview:{flex:1,width:"100%",backgroundColor:"#000"},review:{position:"absolute",bottom:32,left:20,right:20,flexDirection:"row",justifyContent:"space-between",gap:12},secondary:{flex:1,backgroundColor:"#fff",borderRadius:20,paddingVertical:14,alignItems:"center"},secondaryText:{color:"#4F3428",fontWeight:"700"},mainSmall:{flex:1,backgroundColor:C.brown,borderRadius:20,paddingVertical:14,alignItems:"center"}});
