import React,{useState} from 'react';
import {View,Text,TouchableOpacity,TextInput,Switch,Modal,ScrollView,SafeAreaView} from 'react-native';
import {Btn,styles as s} from './JournalScreens';
export function validOpening(value){if(!value)return null;if(!value.recipientIds?.length)return '请选择至少一位亲人';if(value.releaseMode==='date_after_death'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value.releaseDate||'')||isNaN(Date.parse(value.releaseDate))||new Date(value.releaseDate).toISOString().slice(0,10)!==value.releaseDate))return '请填写有效开放日期';return null;}
export default function OpeningSettings({value,onChange,members=[]}){
 const [opened,setOpened]=useState(false);const setting=value||{recipientIds:[],releaseMode:'after_death_confirmation',releaseDate:'',aiFilmAllowed:false};
 const change=patch=>onChange({...setting,...patch});
 return <View style={s.card}><TouchableOpacity accessibilityLabel="设置这条内容的开放权限" onPress={()=>setOpened(true)} style={s.row}><View style={{flex:1}}><Text style={s.h}>开放设置</Text><Text style={s.hint}>{value?`已选 ${value.recipientIds.length} 位亲人 · 身后开放`:'仅自己可见'}</Text></View><Text style={s.h}>›</Text></TouchableOpacity><Modal visible={opened} animationType="slide" onRequestClose={()=>setOpened(false)}><SafeAreaView style={{flex:1,backgroundColor:'#FBF4E9'}}><ScrollView keyboardDismissMode="on-drag" keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Text style={s.title}>这条内容的开放设置</Text><Text style={s.hint}>只对当前档案生效。你可以随时关闭。</Text><View style={s.row}><Text style={s.body}>允许身后向指定亲人开放</Text><Switch value={!!value} onValueChange={v=>onChange(v?setting:null)}/></View>{value&&<><Text style={s.h}>选择亲人</Text>{members.filter(m=>m.id!=='me').map(m=><TouchableOpacity key={m.id} style={[s.row,{paddingVertical:15,borderBottomWidth:1,borderColor:'#EADBC8'}]} onPress={()=>change({recipientIds:setting.recipientIds.includes(m.id)?setting.recipientIds.filter(id=>id!==m.id):[...setting.recipientIds,m.id]})}><Text style={s.body}>{setting.recipientIds.includes(m.id)?'✓ ':'○ '}{m.name}</Text><Text style={s.hint}>{m.relation||'亲人'}</Text></TouchableOpacity>)}{!members.some(m=>m.id!=='me')&&<Text style={s.hint}>先在家族中添加亲人，再设置接收人。</Text>}<Text style={[s.h,{marginTop:20}]}>开放时间</Text>{[['after_death_confirmation','身故多人确认后'],['date_after_death','身故确认后，到指定日期开放']].map(([key,label])=><Btn light key={key} title={(setting.releaseMode===key?'✓ ':'')+label} onPress={()=>change({releaseMode:key})}/>)}{setting.releaseMode==='date_after_death'&&<TextInput value={setting.releaseDate||''} onChangeText={releaseDate=>change({releaseDate})} style={s.input} placeholder="YYYY-MM-DD"/>}<View style={[s.row,{marginTop:15}]}><Text style={[s.body,{flex:1}]}>允许这条内容用于身后故事 / 影片</Text><Switch value={!!setting.aiFilmAllowed} onValueChange={aiFilmAllowed=>change({aiFilmAllowed})}/></View></>}<Text style={s.hint}>实际开放与 AI 生成服务尚未接入；当前设置不会自动公开内容。</Text><Btn title="完成设置，返回编辑" onPress={()=>setOpened(false)}/></ScrollView></SafeAreaView></Modal></View>;
}
