import React,{useEffect,useState} from 'react';
import {Modal,View,Text,TouchableOpacity,ScrollView,StyleSheet} from 'react-native';
import {personDateDays,normalizePersonDate} from './personDates';
export default function PersonDatePicker({visible,value,lunar=false,allowFuture=false,title='选择生日',onConfirm,onClose}){
 const current=new Date().getFullYear()+(allowFuture?10:0),priorYear=Number(normalizePersonDate(value).slice(0,4)),firstYear=priorYear>=1?Math.min(1850,priorYear):1850,[year,setYear]=useState(new Date().getFullYear()),[month,setMonth]=useState(1),[day,setDay]=useState(1);
 useEffect(()=>{if(visible){const parts=normalizePersonDate(value).split('-').map(Number);setYear(parts[0]>=1&&parts[0]<=current?parts[0]:new Date().getFullYear());setMonth(parts[1]>=1&&parts[1]<=12?parts[1]:1);setDay(parts[2]>=1&&parts[2]<=31?parts[2]:1);}},[visible,value]);
 const maxMonth=!allowFuture&&year===current&&!lunar?new Date().getMonth()+1:12,selectedMonth=Math.min(month,maxMonth),maxDay=!allowFuture&&year===current&&selectedMonth===new Date().getMonth()+1&&!lunar?new Date().getDate():31,days=Math.min(personDateDays(year,selectedMonth,lunar),maxDay),selectedDay=Math.min(day,days);
 const column=(label,values,selected,change,suffix)=><View style={s.column}><Text style={s.label}>{label}</Text><ScrollView key={visible+'-'+label} contentOffset={{x:0,y:Math.max(0,values.indexOf(selected)*44-88)}} style={{height:220}} showsVerticalScrollIndicator={false}>{values.map(n=><TouchableOpacity key={n} accessibilityRole="button" accessibilityLabel={`${n}${suffix}`} accessibilityState={{selected:n===selected}} onPress={()=>change(n)} style={[s.item,n===selected&&s.selected]}><Text style={[s.text,n===selected&&s.selectedText]}>{n}{suffix}</Text></TouchableOpacity>)}</ScrollView></View>;
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={s.shade}><View style={s.sheet}><View style={s.head}><TouchableOpacity accessibilityLabel="取消日期选择" onPress={onClose}><Text style={s.action}>取消</Text></TouchableOpacity><Text style={s.title}>{title}{lunar?'（农历）':''}</Text><TouchableOpacity accessibilityLabel="确定日期" onPress={()=>{onConfirm(`${year}-${String(selectedMonth).padStart(2,'0')}-${String(selectedDay).padStart(2,'0')}`);onClose();}}><Text style={s.action}>确定</Text></TouchableOpacity></View><View style={s.columns}>{column('年',Array.from({length:current-firstYear+1},(_,i)=>current-i),year,setYear,'年')}{column('月',Array.from({length:maxMonth},(_,i)=>i+1),selectedMonth,setMonth,'月')}{column('日',Array.from({length:days},(_,i)=>i+1),selectedDay,setDay,'日')}</View><TouchableOpacity accessibilityLabel="日期不知道，暂不填写" onPress={()=>{onConfirm('');onClose();}} style={s.unknown}><Text style={s.hint}>不知道，暂不填写</Text></TouchableOpacity></View></View></Modal>;
}
const s=StyleSheet.create({shade:{flex:1,backgroundColor:'rgba(0,0,0,.35)',justifyContent:'flex-end'},sheet:{backgroundColor:'#fff',borderTopLeftRadius:22,borderTopRightRadius:22,paddingHorizontal:20,paddingBottom:24},head:{height:60,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},action:{fontSize:16,color:'#378BCC',paddingVertical:12},title:{fontSize:17,fontWeight:'600',color:'#292E30'},columns:{flexDirection:'row',gap:12},column:{flex:1},label:{fontSize:12,color:'#929B97',textAlign:'center',marginBottom:8},item:{height:44,alignItems:'center',justifyContent:'center',borderRadius:12},selected:{backgroundColor:'#EAF4FC'},text:{fontSize:17,color:'#5B6360'},selectedText:{color:'#378BCC',fontWeight:'600'},unknown:{alignItems:'center',paddingTop:20,paddingBottom:6},hint:{fontSize:14,color:'#929B97'}});
