import React,{useState} from 'react';
import {View,Text,TextInput,ScrollView,Switch,Alert,TouchableOpacity} from 'react-native';
import {Btn,MediaPreview,attachments,styles as s} from './JournalScreens';
export function HonorsScreen({person,onSave}){
 const own=person.id==='me',items=person.honors||[],[editing,setEditing]=useState(null),[title,setTitle]=useState(''),[date,setDate]=useState(''),[text,setText]=useState(''),[media,setMedia]=useState([]),[visible,setVisible]=useState(true);
 function edit(h){setEditing(h.id);setTitle(h.title);setDate(h.date||'');setText(h.text||'');setMedia(h.media||[]);setVisible(h.visible!==false);}
 function save(){if(!title.trim()){Alert.alert('请填写荣誉名称');return;}if(date&&!/^\d{4}(-\d{2})?(-\d{2})?$/.test(date)){Alert.alert('请填写年份或日期');return;}const h={id:editing||`honor_${Date.now()}`,title:title.trim(),date,text,media,visible};onSave([...items.filter(x=>x.id!==h.id),h]);setEditing(null);setTitle('');setText('');setDate('');setMedia([]);}
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Text style={s.title}>个人荣誉</Text><Text style={s.hint}>{person.name} · 珍藏每一份努力与成就</Text>{items.filter(h=>own||h.visible!==false).map(h=><TouchableOpacity disabled={!own} key={h.id} onPress={()=>edit(h)} style={[s.card,{borderColor:'#D8B776',backgroundColor:'#FFF8E7',borderWidth:1.5}]}><Text style={{fontSize:12,letterSpacing:3,color:'#A27D36'}}>荣 誉 珍 藏</Text><Text style={[s.title,{fontSize:22,marginTop:12}]}>{h.title}</Text><Text style={s.hint}>{h.date}</Text><Text style={s.body}>{h.text}</Text><MediaPreview items={h.media}/>{own&&<Text style={s.hint}>{h.visible===false?'仅自己可见':'展示在人物资料'} · 点击编辑</Text>}</TouchableOpacity>)}{!items.length&&<Text style={s.hint}>还没有记录荣誉。</Text>}{own&&<View style={s.card}><Text style={s.h}>{editing?'编辑荣誉':'记录一份荣誉'}</Text><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="荣誉名称"/><TextInput style={s.input} value={date} onChangeText={setDate} placeholder="获得年份 / 日期"/><TextInput style={s.input} multiline value={text} onChangeText={setText} placeholder="这份荣誉背后的故事"/><MediaPreview items={media} onRemove={i=>setMedia(m=>m.filter((_,j)=>j!==i))}/><Btn light title="添加证书 / 荣誉图片" onPress={async()=>{const a=await attachments();setMedia(m=>[...m,...a.filter(x=>x.type!=='video')]);}}/><View style={s.row}><Text style={s.body}>向有权查看资料的家人展示</Text><Switch value={visible} onValueChange={setVisible}/></View><Btn title="保存荣誉" onPress={save}/></View>}</ScrollView>;
}
export function buildTimeline(person,family){
 const media=(family.media||[]).filter(m=>!m.private&&(m.personIds||[]).includes(person.id)).map(m=>({id:m.id,title:m.event&&m.event!=='未分类'?m.event:'家庭影像',date:m.takenAt||m.createdAt,media:[m]}));
 const honors=(person.honors||[]).filter(h=>person.id==='me'||h.visible!==false).map(h=>({...h,date:h.date}));
 const memories=(person.memories||[]).filter(m=>m.visible).map(m=>({...m,date:m.occurredAt||m.createdAt}));
 return [...media,...honors,...memories,...(person.birthday?[{id:'birth',title:'出生',date:person.birthday}]:[])].filter(m=>m.date&&/^\d{4}/.test(m.date)).sort((a,b)=>b.date.localeCompare(a.date));
}
export function TimelineScreen({person,family}){
 const [year,setYear]=useState('全部'),[opened,setOpened]=useState(null),items=buildTimeline(person,family),years=[...new Set(items.map(x=>x.date.slice(0,4)))];
 return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>{person.name} · 时间线</Text><Text style={s.hint}>根据已记录的日期自动整理。AI 识别事件和补充日期待接入；私密故事不会进入他人视图。</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{['全部',...years].map(y=><TouchableOpacity key={y} onPress={()=>setYear(y)} style={[s.card,{marginRight:8,padding:12,backgroundColor:y===year?'#EEE0C9':'#fff'}]}><Text>{y}</Text></TouchableOpacity>)}</ScrollView>{items.filter(x=>year==='全部'||x.date.startsWith(year)).map(m=><TouchableOpacity key={m.id} style={[s.card,{borderLeftWidth:3,borderLeftColor:'#B58B5C'}]} onPress={()=>setOpened(opened===m.id?null:m.id)}><Text style={s.hint}>{m.date.slice(0,10)}</Text><Text style={s.h}>{m.title||'人生记忆'}</Text>{opened===m.id?<><Text style={s.body}>{m.text}</Text><MediaPreview items={m.media}/></>:<Text style={s.hint}>展开查看 ›</Text>}</TouchableOpacity>)}{!items.length&&<Text style={s.hint}>为照片补充人物和日期后，记忆会自动出现在这里。</Text>}</ScrollView>;
}
export function AdviceScreen({person,onSave}){
 const own=person.id==='me',[text,setText]=useState(person.advice||'');return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>给晚辈的话</Text><Text style={s.hint}>{person.name} · 经验、忠告与家风</Text>{own?<><TextInput multiline style={[s.input,{minHeight:220,textAlignVertical:'top'}]} value={text} onChangeText={setText} placeholder="想留给晚辈的话…"/><Text style={s.hint}>保存后向有权查看你资料的家人展示。私密经历请写在「我的故事」。</Text><Btn title="保存给晚辈的话" onPress={()=>onSave(text)}/></>:<View style={s.card}><Text style={s.body}>{person.advice||'暂时还没有留下内容。'}</Text></View>}</ScrollView>;
}
export function MemorialMemoriesScreen({person,media:familyMedia=[],onSave}){
 const [title,setTitle]=useState(''),[text,setText]=useState(''),[date,setDate]=useState(''),[media,setMedia]=useState([]);
 if(!person?.dead)return <View style={s.page}><Text style={s.title}>人物尚未确认为已故</Text></View>;
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Text style={s.title}>{person.name} · 纪念</Text><Text style={s.hint}>留下家人的回忆。补充内容标明记录人，原有亲子关系保持不变。</Text><View style={s.card}><Text style={s.h}>生平与家庭影像</Text><Text style={s.hint}>{person.birthday?'出生于 '+person.birthday:'出生日期待补充'}</Text><MediaPreview items={familyMedia.filter(m=>!m.private&&(m.personIds||[]).includes(person.id))}/>{!familyMedia.some(m=>!m.private&&(m.personIds||[]).includes(person.id))&&<Text style={s.hint}>在家庭相册确认照片中的人物后，影像会出现在这里。</Text>}</View>{(person.memories||[]).map(m=><View key={m.id} style={s.card}><Text style={s.h}>{m.title}</Text><Text style={s.hint}>{m.occurredAt||'日期待补充'} · {m.authorName||'家人'}整理</Text>{m.visible||m.authorId==='me'?<><Text style={s.body}>{m.text}</Text><MediaPreview items={m.media}/></>:<Text style={s.hint}>记录未开放</Text>}{m.authorId==='me'&&<View style={s.row}><Text>展示这段回忆</Text><Switch value={!!m.visible} onValueChange={v=>onSave((person.memories||[]).map(x=>x.id===m.id?{...x,visible:v}:x))}/></View>}</View>)}<View style={s.card}><Text style={s.h}>补充人生经历</Text><TextInput value={title} onChangeText={setTitle} style={s.input} placeholder="这段回忆的标题"/><TextInput value={date} onChangeText={setDate} style={s.input} placeholder="发生日期 YYYY-MM-DD（可留空）"/><TextInput multiline value={text} onChangeText={setText} style={[s.input,{minHeight:130}]} placeholder="记录你知道的经历…"/><MediaPreview items={media}/><Btn light title="添加图片 / 视频" onPress={async()=>{const a=await attachments();setMedia(m=>[...m,...a]);}}/><Btn title="保存回忆（默认关闭展示）" onPress={()=>{if(!text.trim()&&!media.length)return;if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||isNaN(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date)){Alert.alert('请填写有效日期');return;}onSave([...(person.memories||[]),{id:`mem_${Date.now()}`,title:title||'家人回忆',text,media,occurredAt:date,createdAt:new Date().toISOString(),authorId:'me',authorName:'我',visible:false}]);setTitle('');setText('');setDate('');setMedia([]);}}/></View></ScrollView>;
}
