import React,{useState} from "react";
import {View,Text,TouchableOpacity,StyleSheet,Alert,Image,ScrollView,TextInput} from "react-native";
import {pickImagesAndVideos} from "./mediaPicker";
import JiaIcon from "./JiaIcon";
const C={bg:"#FFFDF9",card:"#FFFFFF",brown:"#A85E37",deep:"#2D1B14",muted:"#8D7E75",line:"#EEE7E0"};
export default function UploadScreen({onAdd,onOldPhoto,isMember=false}){
 const [picked,setPicked]=useState([]),[note,setNote]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10));
 async function pick(mode="manual"){
  if(mode==="ai"&&!isMember){Alert.alert("AI 智能上传 · 会员","开通会员后，可自动识别人像、时间、地点并分类。");return}
  const r=await pickImagesAndVideos();
  if(r.permissionDenied){Alert.alert("需要照片权限","允许访问照片后才能选择照片或视频。");return}
  if(!r.assets.length)return;
  const now=new Date().toISOString();
  onAdd?.(r.assets.map((a,i)=>({id:`m_${Date.now()}_${i}`,uri:a.uri,type:a.type||"image",width:a.width,height:a.height,fileName:a.fileName||"",createdAt:now,takenAt:now,event:"未分类",personIds:[],private:false,source:"device_picker",aiMode:mode==="ai"})));
 }
 if(picked.length){const save=()=>{const now=new Date().toISOString();onAdd?.(picked.map((a,i)=>({id:`m_${Date.now()}_${i}`,uri:a.uri,type:a.type||"image",width:a.width,height:a.height,fileName:a.fileName||"",createdAt:now,takenAt:date,event:note||"未分类",personIds:[],private:false,source:"device_picker",aiMode:!!a.aiMode})));setPicked([]);};return <ScrollView style={s.previewScreen} contentContainerStyle={s.previewPage}><View style={s.previewHead}><TouchableOpacity onPress={()=>setPicked([])}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.previewTitle}>上传照片</Text><View style={{width:28}}/></View><View style={s.previewGrid}>{picked.map((a,i)=><View key={a.uri+i} style={s.previewCell}><Image source={{uri:a.uri}} style={s.previewImg}/><TouchableOpacity style={s.remove} onPress={()=>setPicked(v=>v.filter((_,x)=>x!==i))}><Text style={s.removeText}>×</Text></TouchableOpacity></View>)}<TouchableOpacity style={s.addMore} onPress={()=>pick("manual")}><JiaIcon name="plus" size={26} color="#8B7568"/><Text style={s.addMoreText}>添加</Text></TouchableOpacity></View><View style={s.formCard}><View style={s.formRow}><Text style={s.formLabel}>拍摄时间</Text><TextInput value={date} onChangeText={setDate} style={s.formInput}/></View><View style={s.formRow}><Text style={s.formLabel}>地点</Text><Text style={s.formPlaceholder}>添加地点  ›</Text></View><View style={s.formRow}><Text style={s.formLabel}>照片里有谁</Text><Text style={s.formPlaceholder}>添加人物  ›</Text></View><View style={[s.formRow,{borderBottomWidth:0}]}><Text style={s.formLabel}>备注</Text><TextInput value={note} onChangeText={setNote} placeholder="写点什么..." placeholderTextColor="#B1A49B" style={s.formInput}/></View></View><TouchableOpacity onPress={save} style={s.doneBtn}><Text style={s.doneText}>完成</Text></TouchableOpacity></ScrollView>}
 return <View style={s.screen}><View style={s.dim}/><View style={s.sheet}><View style={s.handle}/><Text style={s.title}>选择上传方式</Text>
  <TouchableOpacity style={s.row} onPress={()=>pick("manual")}><View style={[s.icon,{backgroundColor:"#E9F5FF"}]}><JiaIcon name="album" size={25} color="#2695E8"/></View><View style={s.flex}><Text style={s.h}>手动上传</Text><Text style={s.p}>从手机相册选择照片或视频</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>
  <TouchableOpacity style={s.row} onPress={()=>pick("ai")}><View style={[s.icon,{backgroundColor:"#F1ECFF"}]}><JiaIcon name="sparkles" size={25} color="#8067E8"/></View><View style={s.flex}><View style={s.inline}><Text style={s.h}>AI 智能上传（会员）</Text><Text style={s.crown}>♛</Text></View><Text style={s.p}>自动识别人像、时间、地点并分类</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>
  <TouchableOpacity style={s.row} onPress={()=>isMember?onOldPhoto?.():Alert.alert("扫描老照片 · 会员功能","开通会员后可使用扫描老照片与修复功能。")}><View style={[s.icon,{backgroundColor:"#FFF0EA"}]}><JiaIcon name="scan" size={25} color="#F06448"/></View><View style={s.flex}><Text style={s.h}>扫描老照片</Text><Text style={s.p}>拍照或扫描旧照片，可自动修复</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>
  <TouchableOpacity style={s.cancel}><Text style={s.cancelText}>取消</Text></TouchableOpacity>
 </View></View>;
}
const s=StyleSheet.create({screen:{flex:1,justifyContent:"flex-end",backgroundColor:"#F7F1E8"},dim:{...StyleSheet.absoluteFillObject,backgroundColor:"rgba(0,0,0,.38)"},sheet:{backgroundColor:C.bg,borderTopLeftRadius:24,borderTopRightRadius:24,paddingHorizontal:16,paddingTop:9,paddingBottom:24},handle:{width:38,height:4,borderRadius:2,backgroundColor:"#D8D0C9",alignSelf:"center",marginBottom:11},title:{fontSize:18,fontWeight:"800",color:C.deep,textAlign:"center",marginBottom:12},row:{minHeight:72,backgroundColor:C.card,borderRadius:14,paddingHorizontal:12,marginBottom:8,flexDirection:"row",alignItems:"center",gap:12,borderWidth:1,borderColor:C.line},icon:{width:45,height:45,borderRadius:12,alignItems:"center",justifyContent:"center"},flex:{flex:1},inline:{flexDirection:"row",alignItems:"center",gap:6},h:{fontSize:15,fontWeight:"800",color:C.deep},p:{fontSize:11,color:C.muted,marginTop:4},arrow:{fontSize:25,color:"#A89B92"},crown:{fontSize:16,color:"#E4A118"},cancel:{height:50,borderRadius:14,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",marginTop:3},cancelText:{fontSize:15,fontWeight:"700",color:C.deep},previewScreen:{flex:1,backgroundColor:"#FFFDF9"},previewPage:{paddingHorizontal:16,paddingTop:10,paddingBottom:110},previewHead:{height:48,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:34,color:"#2D1B14"},previewTitle:{fontSize:18,fontWeight:"800",color:"#2D1B14"},previewGrid:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:12},previewCell:{width:"31.8%",aspectRatio:1,borderRadius:9,overflow:"hidden"},previewImg:{width:"100%",height:"100%"},remove:{position:"absolute",right:5,top:5,width:21,height:21,borderRadius:11,backgroundColor:"rgba(30,20,15,.7)",alignItems:"center",justifyContent:"center"},removeText:{color:"#fff",fontSize:16,lineHeight:18},addMore:{width:"31.8%",aspectRatio:1,borderRadius:9,borderWidth:1,borderColor:"#E4D8CE",borderStyle:"dashed",alignItems:"center",justifyContent:"center",backgroundColor:"#FCF7F1"},addMoreText:{fontSize:11,color:"#8B7568",marginTop:4},formCard:{backgroundColor:"#fff",borderRadius:16,marginTop:20,paddingHorizontal:14,borderWidth:1,borderColor:"#EEE7E0"},formRow:{minHeight:54,flexDirection:"row",alignItems:"center",borderBottomWidth:1,borderBottomColor:"#F0E8E1"},formLabel:{width:88,fontSize:13,fontWeight:"700",color:"#3A271E"},formInput:{flex:1,textAlign:"right",fontSize:12,color:"#765D50",paddingVertical:10},formPlaceholder:{flex:1,textAlign:"right",fontSize:12,color:"#9A8B81"},doneBtn:{height:50,borderRadius:25,backgroundColor:"#A85E37",alignItems:"center",justifyContent:"center",marginTop:22},doneText:{fontSize:15,fontWeight:"800",color:"#fff"},});
