import React,{useState,useEffect} from 'react';
import {View,Text,ScrollView,TextInput,Modal,Alert,Switch,Platform} from 'react-native';
import {useAudioRecorder,useAudioRecorderState,useAudioPlayer,RecordingPresets,AudioModule,setAudioModeAsync} from 'expo-audio';
import {Btn,styles as s} from './JournalScreens';
const prompts=['你好，我是你的家人。这是我留下的声音，希望未来你听见时，能想起我们在一起的日子。','小时候，我最难忘的一件事，是和家人一起度过的那个夏天。','我希望你平安，也希望你勇敢。遇到困难时，别忘记还有爱你的人。'];
function Playback({uri}){const player=useAudioPlayer(uri);return <Btn light title="试听 / 重播" onPress={async()=>{await setAudioModeAsync({allowsRecording:false,playsInSilentMode:true});await player.seekTo(0);player.play();}}/>;}
export default function VoiceMemoryScreen({items=[],onSave}){
 const recorder=useAudioRecorder({...RecordingPresets.HIGH_QUALITY,directory:'document'}),state=useAudioRecorderState(recorder),[modal,setModal]=useState(false),[index,setIndex]=useState(0),[guided,setGuided]=useState(false),[title,setTitle]=useState(''),[draft,setDraft]=useState(null),[allow,setAllow]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(recorder.isRecording)recorder.stop().catch(()=>{});},[recorder]);
 async function record(){try{const p=await AudioModule.requestRecordingPermissionsAsync();if(!p.granted){Alert.alert('需要麦克风权限');return;}setDraft(null);await setAudioModeAsync({allowsRecording:true,playsInSilentMode:true});await recorder.prepareToRecordAsync();recorder.record();}catch(e){Alert.alert('未能开始录音',e.message);}}
 async function stop(){setBusy(true);try{await recorder.stop();const uri=recorder.uri;if(Platform.OS==='web'){const blob=await (await fetch(uri)).blob();const encoded=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});setDraft(encoded);}else setDraft(uri);await setAudioModeAsync({allowsRecording:false,playsInSilentMode:true});}catch(e){Alert.alert('未能保存录音',e.message);}finally{setBusy(false);}}
 return <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.page}><Text style={s.title}>留下我的声音</Text><Text style={s.hint}>录音默认仅自己可见。引导跟读与自由讲述均可保存，声音合成服务尚未接入。</Text><Btn light title="打开引导跟读窗口" onPress={()=>{setGuided(true);setModal(true);}}/><Btn light title="自由录入我的故事" onPress={()=>{setGuided(false);setModal(true);}}/><Modal visible={modal} animationType="slide" onRequestClose={()=>{if(!state.isRecording)setModal(false);}}><ScrollView contentContainerStyle={[s.page,{paddingTop:55}]}><Text style={s.title}>{guided?'跟读，留下声音':'自由讲述'}</Text>{guided?<><Text style={[s.body,{fontSize:23,lineHeight:38}]}>{prompts[index]}</Text><Btn light disabled={state.isRecording} title="换一句" onPress={()=>setIndex(i=>(i+1)%prompts.length)}/></>:<Text style={s.hint}>讲讲你的童年、家人，或今天发生的事。</Text>}<TextInput value={title} onChangeText={setTitle} style={s.input} placeholder="录音名称（可不填）"/><Text style={s.body}>{state.isRecording?`正在录音 · ${Math.round(state.durationMillis/1000)} 秒`:'找一个安静的地方，自然说话。'}</Text><Btn disabled={busy} title={state.isRecording?'停止录音':'开始录音 / 重录'} onPress={state.isRecording?stop:record}/>{draft&&<><Playback key={draft} uri={draft}/><View style={s.row}><Text style={[s.body,{flex:1}]}>允许未来用于自己的故事旁白与声音合成</Text><Switch value={allow} onValueChange={setAllow}/></View><Btn title="保存这段声音" onPress={()=>{onSave({id:`voice_${Date.now()}`,uri:draft,title:title||'我的声音',prompt:guided?prompts[index]:null,createdAt:new Date().toISOString(),voiceUseAllowed:allow,private:true});setDraft(null);setTitle('');setAllow(false);setModal(false);}}/></>}<Btn light disabled={state.isRecording} title="关闭窗口" onPress={()=>setModal(false)}/></ScrollView></Modal>{items.map(v=><View key={v.id} style={s.card}><Text style={s.h}>{v.title}</Text><Text style={s.hint}>{v.createdAt.slice(0,10)} · {v.voiceUseAllowed?'已允许未来旁白用途':'仅保存原声'}</Text><Playback uri={v.uri}/></View>)}</ScrollView>;
}
