import React,{useEffect,useRef,useState} from 'react';
import {View,Text,TouchableOpacity,Modal,ScrollView,StyleSheet,PanResponder,useWindowDimensions,Platform} from 'react-native';
import XiaojiaArtwork from './XiaojiaArtwork';
import XiaojiaChatScreen from './XiaojiaChatScreen';
import AsyncStorage from '@react-native-async-storage/async-storage';
const destinations=[['家庭相册','album'],['家族树','tree'],['重要日子','days'],['家讯','chat'],['我的人生','lifeInterview']];
const key='jia-assistant-preferences-v1';
export default function XiaojiaAssistant({screen,onGo,family}){
 const {width,height}=useWindowDimensions(),[open,setOpen]=useState(false),[hidden,setHidden]=useState(false),[ready,setReady]=useState(false),[welcome,setWelcome]=useState(false),[error,setError]=useState('');
 const prefs=useRef({look:'robot',welcomed:false}),queue=useRef(Promise.resolve()),dimensions=useRef({width,height}),moved=useRef(false),origin=useRef({x:0,y:0});
 const [position,setPosition]=useState({x:width-72,y:height-180}),pos=useRef(position);
 dimensions.current={width,height};
 const bound=(x,y)=>({x:Math.max(8,Math.min(dimensions.current.width-80,x)),y:Math.max(75,Math.min(dimensions.current.height-175,y))});
 const move=p=>{pos.current=p;setPosition(p)};
 useEffect(()=>{let active=true;AsyncStorage.getItem(key).then(raw=>{if(!active)return;try{const p=JSON.parse(raw||'null');if(p){prefs.current={look:'robot',welcomed:!!p.welcomed}}}catch{}setReady(true)}).catch(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 useEffect(()=>{move(bound(pos.current.x,pos.current.y))},[width,height]);
 useEffect(()=>{if(ready&&screen==='home'&&!prefs.current.welcomed){setWelcome(true);setOpen(true)}},[ready,screen]);
 useEffect(()=>{setHidden(false);if(screen!=='home'){setOpen(false);setWelcome(false)}},[screen]);
 async function save(change){setError('');const work=queue.current.catch(()=>{}).then(async()=>{const next={...prefs.current,...change};await AsyncStorage.setItem(key,JSON.stringify(next));prefs.current=next});queue.current=work;try{await work;return true}catch{setError('设置未保存，请重试。');return false}}
 async function close(){if(welcome&&!await save({welcomed:true}))return;setWelcome(false);setOpen(false)}
 const start=()=>{origin.current=pos.current;moved.current=false};
 const drag=(dx,dy)=>{if(Math.abs(dx)+Math.abs(dy)>6)moved.current=true;if(moved.current)move(bound(origin.current.x+dx,origin.current.y+dy))};
 const finish=()=>{if(moved.current)move(bound(pos.current.x<dimensions.current.width/2?8:dimensions.current.width-80,pos.current.y));else setOpen(true)};
 const pan=useRef(PanResponder.create({onStartShouldSetPanResponder:()=>true,onMoveShouldSetPanResponder:()=>true,onPanResponderGrant:start,onPanResponderMove:(_,g)=>drag(g.dx,g.dy),onPanResponderRelease:finish,onPanResponderTerminate:()=>move(bound(pos.current.x,pos.current.y))})).current;
 const pointer=useRef(null);
 const webDrag={onPointerDown:e=>{if(e.nativeEvent.isPrimary===false||pointer.current)return;pointer.current={id:e.nativeEvent.pointerId,x:e.nativeEvent.clientX,y:e.nativeEvent.clientY};e.currentTarget.setPointerCapture?.(e.nativeEvent.pointerId);start()},onPointerMove:e=>{if(pointer.current&&pointer.current.id===e.nativeEvent.pointerId)drag(e.nativeEvent.clientX-pointer.current.x,e.nativeEvent.clientY-pointer.current.y)},onPointerUp:()=>{if(pointer.current){pointer.current=null;finish()}},onPointerCancel:()=>{pointer.current=null;move(bound(pos.current.x,pos.current.y))}};
 return <>
 {screen==='home'&&hidden&&<TouchableOpacity accessibilityRole="button" accessibilityLabel="显示小家" onPress={()=>setHidden(false)} style={s.restore}><Text style={s.link}>显示小家</Text></TouchableOpacity>}
 {!hidden&&<View style={[s.floating,{left:position.x,top:position.y}]}><View accessibilityRole="button" accessibilityLabel="打开小家浮动窗口" tabIndex={0} onKeyDown={e=>{if(e.nativeEvent.key==='Enter')setOpen(true)}} style={[s.orb,Platform.OS==='web'&&{touchAction:'none',cursor:'grab',userSelect:'none'}]} {...(Platform.OS==='web'?webDrag:pan.panHandlers)}><XiaojiaArtwork width={65}/></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="隐藏小家" onPress={()=>setHidden(true)} style={s.hide}><Text style={s.link}>×</Text></TouchableOpacity>{screen==='home'&&<View pointerEvents="none" style={[s.prompt,{left:position.x<width/2?65:-200}]}><Text style={s.promptText}>今天，有什么想聊的吗？</Text></View>}</View>}

 <Modal visible={open} transparent animationType="fade" onRequestClose={close}><View style={s.backdrop}><View accessibilityViewIsModal style={[s.window,!welcome&&{height:"80%"}]}>{!welcome?<><XiaojiaChatScreen family={family} onBack={close}/><View style={{flexDirection:"row",padding:12,gap:12}}><TouchableOpacity onPress={()=>{setOpen(false);onGo("lifeInterview")}}><Text style={s.link}>展开聊天</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setOpen(false);onGo("album")}}><Text style={s.link}>家庭相册</Text></TouchableOpacity></View></>:<><View style={s.header}><View style={{flexDirection:"row",alignItems:"center",gap:10}}><XiaojiaArtwork width={35}/><Text style={s.title}>小家</Text></View><TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭小家窗口" onPress={close} style={s.close}><Text style={s.link}>关闭</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.greeting}>欢迎回家，我是小家。今天想聊些什么？</Text><View style={s.routes}>{destinations.map(([label,target])=><TouchableOpacity key={target} accessibilityRole="button" accessibilityLabel={'小家打开'+label} onPress={async()=>{if(welcome&&!await save({welcomed:true}))return;setOpen(false);setWelcome(false);onGo(target)}} style={s.route}><Text style={s.link}>{label}</Text></TouchableOpacity>)}</View><Text style={s.note}>可以打开家庭页面，或聊聊你的人生。智能聊天、语音控制与播报尚未接通。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</ScrollView></>}</View></View></Modal>
 </>
}
const s=StyleSheet.create({prompt:{position:'absolute',top:15,width:200,backgroundColor:'#F0F6FF',borderWidth:1,borderColor:'#CBDFF9',borderRadius:24,padding:12},promptText:{fontSize:13,color:'#172236'},floating:{position:'absolute',zIndex:30,width:70,alignItems:'center'},orb:{width:70,height:74,alignItems:'center',justifyContent:'center'},hideButton:{},face:{fontSize:31},hide:{position:'absolute',right:-2,top:-6,padding:6,backgroundColor:'#FFFFFF',borderRadius:16},restore:{position:'absolute',right:12,bottom:86,padding:10,backgroundColor:'#EEF6FC',borderRadius:16},link:{fontSize:15,color:'#287CB8'},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.18)',justifyContent:'center',alignItems:'center',padding:20},window:{width:'100%',maxWidth:480,maxHeight:'80%',backgroundColor:'#FFFFFF',borderRadius:24,overflow:'hidden'},header:{padding:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#EDF0F3'},title:{fontSize:21,fontWeight:'600',color:'#292E30'},close:{padding:8},content:{padding:18,gap:16},greeting:{fontSize:18,lineHeight:28,color:'#292E30'},looks:{flexDirection:'row',flexWrap:'wrap',gap:8},look:{minWidth:75,padding:10,borderRadius:15,alignItems:'center',borderWidth:1,borderColor:'#E5EBEF'},selected:{backgroundColor:'#ECF5FE',borderColor:'#378BCC'},emoji:{fontSize:28},label:{fontSize:13,color:'#292E30',marginTop:6},note:{fontSize:13,lineHeight:21,color:'#6F7E88'},routes:{flexDirection:'row',flexWrap:'wrap',gap:10},route:{paddingVertical:12,paddingHorizontal:15,backgroundColor:'#F1F7FC',borderRadius:14},error:{color:'#B84C45',fontSize:14}});
