import React,{useEffect,useRef,useState} from 'react';
import {View,Text,TouchableOpacity,Modal,ScrollView,StyleSheet,PanResponder,useWindowDimensions} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
const looks=[['robot','🤖','小机器人'],['cat','🐱','小猫'],['dog','🐶','小狗'],['bear','🐻','小熊'],['rabbit','🐰','小兔']];
const destinations=[['家庭相册','album'],['家族树','tree'],['重要日子','days'],['家讯','chat'],['我的人生','lifeInterview']];
const key='jia-assistant-preferences-v1';
export default function XiaojiaAssistant({screen,onGo}){
 const {width,height}=useWindowDimensions(),[open,setOpen]=useState(false),[hidden,setHidden]=useState(false),[look,setLook]=useState('robot'),[ready,setReady]=useState(false),[welcome,setWelcome]=useState(false),[error,setError]=useState('');
 const prefs=useRef({look:'robot',welcomed:false}),queue=useRef(Promise.resolve()),moved=useRef(false),origin=useRef({x:0,y:0});
 const [position,setPosition]=useState({x:width-72,y:height-180}),pos=useRef(position);
 const bound=(x,y)=>({x:Math.max(8,Math.min(width-64,x)),y:Math.max(75,Math.min(height-150,y))});
 const move=p=>{pos.current=p;setPosition(p)};
 useEffect(()=>{let active=true;AsyncStorage.getItem(key).then(raw=>{if(!active)return;try{const p=JSON.parse(raw||'null');if(p){prefs.current={look:looks.some(x=>x[0]===p.look)?p.look:'robot',welcomed:!!p.welcomed};setLook(prefs.current.look)}}catch{}setReady(true)}).catch(()=>{if(active)setReady(true)});return()=>{active=false}},[]);
 useEffect(()=>{move(bound(pos.current.x,pos.current.y))},[width,height]);
 useEffect(()=>{if(ready&&screen==='home'&&!prefs.current.welcomed){setWelcome(true);setOpen(true)}},[ready,screen]);
 useEffect(()=>{setHidden(false);if(screen!=='home'){setOpen(false);setWelcome(false)}},[screen]);
 async function save(change){setError('');const next={...prefs.current,...change};const work=queue.current.catch(()=>{}).then(()=>AsyncStorage.setItem(key,JSON.stringify(next)));queue.current=work;try{await work;prefs.current=next;return true}catch{setError('设置未保存，请重试。');return false}}
 async function close(){if(welcome&&!await save({welcomed:true}))return;setWelcome(false);setOpen(false)}
 const pan=PanResponder.create({onStartShouldSetPanResponder:()=>false,onMoveShouldSetPanResponder:(_,g)=>Math.abs(g.dx)+Math.abs(g.dy)>8,onPanResponderGrant:()=>{origin.current=pos.current;moved.current=true},onPanResponderMove:(_,g)=>move(bound(origin.current.x+g.dx,origin.current.y+g.dy)),onPanResponderRelease:()=>{move(bound(pos.current.x<width/2?8:width-64,pos.current.y));setTimeout(()=>{moved.current=false},100)}});
 const icon=looks.find(x=>x[0]===look)?.[1]||'🤖';
 return <>
 {screen==='home'&&hidden&&<TouchableOpacity accessibilityRole="button" accessibilityLabel="显示小家" onPress={()=>setHidden(false)} style={s.restore}><Text style={s.link}>显示小家</Text></TouchableOpacity>}
 {!hidden&&<View style={[s.floating,{left:position.x,top:position.y}]} {...pan.panHandlers}><TouchableOpacity accessibilityRole="button" accessibilityLabel="打开小家浮动窗口" onPress={()=>{if(!moved.current)setOpen(true)}} style={s.orb}><Text style={s.face}>{icon}</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="隐藏小家" onPress={()=>setHidden(true)} style={s.hide}><Text style={s.link}>隐藏</Text></TouchableOpacity></View>}
 <Modal visible={open} transparent animationType="fade" onRequestClose={close}><View style={s.backdrop}><View accessibilityViewIsModal style={s.window}><View style={s.header}><Text style={s.title}>{icon} 小家</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭小家窗口" onPress={close} style={s.close}><Text style={s.link}>关闭</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Text style={s.greeting}>{welcome?'欢迎回家，选一个你喜欢的小家吧。':'今天想去哪里，或者聊聊你的人生？'}</Text><View style={s.looks}>{looks.map(([id,emoji,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={'选择'+label} accessibilityState={{selected:look===id}} onPress={async()=>{if(await save({look:id}))setLook(id)}} style={[s.look,look===id&&s.selected]}><Text style={s.emoji}>{emoji}</Text><Text style={s.label}>{label}</Text></TouchableOpacity>)}</View><Text style={s.note}>形象为首版占位，之后可换成专属动画形象。</Text><View style={s.routes}>{destinations.map(([label,target])=><TouchableOpacity key={target} accessibilityRole="button" accessibilityLabel={'小家打开'+label} onPress={async()=>{if(welcome&&!await save({welcomed:true}))return;setOpen(false);setWelcome(false);onGo(target)}} style={s.route}><Text style={s.link}>{label}</Text></TouchableOpacity>)}</View><Text style={s.note}>现在可选择形象、打开页面和进入人生问答。智能聊天、语音控制与播报正在接入。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</ScrollView></View></View></Modal>
 </>
}
const s=StyleSheet.create({floating:{position:'absolute',zIndex:30,width:56,alignItems:'center'},orb:{width:56,height:56,borderRadius:28,backgroundColor:'#E9F4FF',borderWidth:1,borderColor:'#B9D9F5',alignItems:'center',justifyContent:'center',elevation:5},face:{fontSize:31},hide:{padding:8},restore:{position:'absolute',right:12,bottom:86,padding:10,backgroundColor:'#EEF6FC',borderRadius:16},link:{fontSize:15,color:'#287CB8'},backdrop:{flex:1,backgroundColor:'rgba(0,0,0,.18)',justifyContent:'center',alignItems:'center',padding:20},window:{width:'100%',maxWidth:480,maxHeight:'80%',backgroundColor:'#FFFFFF',borderRadius:24,overflow:'hidden'},header:{padding:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#EDF0F3'},title:{fontSize:21,fontWeight:'600',color:'#292E30'},close:{padding:8},content:{padding:18,gap:16},greeting:{fontSize:18,lineHeight:28,color:'#292E30'},looks:{flexDirection:'row',flexWrap:'wrap',gap:8},look:{minWidth:75,padding:10,borderRadius:15,alignItems:'center',borderWidth:1,borderColor:'#E5EBEF'},selected:{backgroundColor:'#ECF5FE',borderColor:'#378BCC'},emoji:{fontSize:28},label:{fontSize:13,color:'#292E30',marginTop:6},note:{fontSize:13,lineHeight:21,color:'#6F7E88'},routes:{flexDirection:'row',flexWrap:'wrap',gap:10},route:{paddingVertical:12,paddingHorizontal:15,backgroundColor:'#F1F7FC',borderRadius:14},error:{color:'#B84C45',fontSize:14}});
