import React,{useEffect,useState,useRef} from 'react';
import {View,Text,TouchableOpacity,ScrollView,TextInput,StyleSheet,KeyboardAvoidingView,Platform} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import XiaojiaArtwork from './XiaojiaArtwork';
import {interviewQuestions} from './lifeInterview';
const key='jia-xiaojia-conversations-v1';
export default function XiaojiaChatScreen({family,onBack,bottomInset=0,compact=false}){
 const [mode,setMode]=useState('self'),[data,setData]=useState({messages:[],answered:[],skipped:[]}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(null),[qa,setQa]=useState([]),[choosing,setChoosing]=useState(false);
 const [compactAnswered,setCompactAnswered]=useState(false);
 const lock=useRef(false),scroller=useRef();
 const members=family?.members||[],relative=members.find(p=>p.id===selected)||members.find(p=>p.id!=='me')||members[0];
 const question=interviewQuestions.find(q=>!data.answered.includes(q.id)&&!data.skipped.includes(q.id));
 useEffect(()=>{let active=true;AsyncStorage.getItem(key).then(raw=>{if(!active)return;if(raw){const p=JSON.parse(raw);if(Array.isArray(p.messages)&&Array.isArray(p.answered))setData({messages:p.messages.filter(m=>m&&typeof m.text==='string'&&typeof m.question==='string'),answered:p.answered.filter(x=>typeof x==='string'),skipped:Array.isArray(p.skipped)?p.skipped.filter(x=>typeof x==='string'):[]})}setLoaded(true)}).catch(()=>{if(active){setError('聊天记录读取失败，请退出后重试。')}});return()=>{active=false}},[]);
 async function persist(next){await AsyncStorage.setItem(key,JSON.stringify(next));setData(next)}
 async function send(text=draft){if(!text.trim()||lock.current||!loaded)return;lock.current=true;setBusy(true);setError('');try{if(mode==='self'){const next={...data,messages:[...data.messages,{id:Date.now(),question:question?.text||'今天有什么想聊的事？',questionId:question?.id||null,text:text.trim(),source:'self',createdAt:new Date().toISOString()}],answered:question?[...data.answered,question.id]:data.answered};await persist(next);setDraft('');if(compact)setCompactAnswered(true)}else{const p=relative;if(!p)throw Error('没有可查看的家人');let answer;if(/几|多少/.test(text)&&/人|口/.test(text))answer=`当前家庭空间登记了 ${members.length} 位家人：${members.map(x=>x.name).join('、')}。这是登记成员，并不代表现实中全部家庭人口。`;else if(/生日|出生/.test(text))answer=p.birthday?`${p.name}的资料中，生日是 ${p.birthday}。`:'这位家人的资料里还没有生日记录。';else answer=`目前可查看${p.name}的基本资料；尚未接通 AI，暂时不能分析这段经历。`;setQa(v=>[...v,{id:Date.now(),question:text.trim(),answer}]);setDraft('')}}catch{setError('未保存成功，输入仍保留，请重试。')}finally{lock.current=false;setBusy(false)}}
 async function skip(){setCompactAnswered(false);if(!question||lock.current)return;lock.current=true;setBusy(true);try{await persist({...data,skipped:[...data.skipped,question.id]})}catch{setError('未能更换问题，请重试。')}finally{lock.current=false;setBusy(false)}}
 if(compact)return <View style={{padding:18,width:'100%'}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8}}><Text style={{fontSize:14,fontWeight:'600',color:'#347EF0'}}>小家 · 欢迎回家</Text><TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭欢迎问答" onPress={onBack} style={{padding:8,marginRight:-6}}><Text style={{fontSize:22,color:'#788596'}}>×</Text></TouchableOpacity></View>
 {!loaded?<Text style={s.note}>正在读取问答…</Text>:compactAnswered?<View style={{gap:16}}><Text style={[s.body,{fontSize:17}]}>谢谢你，这段经历我记下了。还想再聊一点吗？</Text><View style={{flexDirection:'row',gap:10}}><TouchableOpacity accessibilityRole="button" accessibilityLabel="下一题" onPress={()=>setCompactAnswered(false)} style={s.chip}><Text style={s.chipText}>下一题</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭欢迎问答" onPress={onBack} style={s.secondary}><Text style={s.muted}>关闭</Text></TouchableOpacity></View></View>:question?<View style={{gap:16}}><Text style={[s.body,{fontSize:18,lineHeight:28}]}>{question.text}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{question.options.filter(([id])=>!['unsure','skip'].includes(id)).map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={'欢迎问答选择'+label} disabled={busy} onPress={()=>send(label)} style={[s.chip,{paddingHorizontal:13,paddingVertical:10,backgroundColor:'#F5F9FF'}]}><Text style={s.chipText}>{label}</Text></TouchableOpacity>)}</View><View style={{flexDirection:'row',gap:20}}><TouchableOpacity accessibilityRole="button" accessibilityLabel="下一题" disabled={busy} onPress={skip}><Text style={s.muted}>下一题</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭欢迎问答" onPress={onBack}><Text style={s.muted}>关闭</Text></TouchableOpacity></View></View>:<Text style={s.body}>这些问题已经聊过了。你随时可以在小家里讲讲新的经历。</Text>}{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</View>;
 return <KeyboardAvoidingView style={[s.root,{paddingBottom:bottomInset}]} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><TouchableOpacity accessibilityRole="button" accessibilityLabel="返回首页" onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></TouchableOpacity><XiaojiaArtwork width={35}/><Text style={s.title}>小家</Text></View><View style={s.tabs}>{[['self','聊聊我的人生'],['family','了解家人']].map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={label} onPress={()=>{setMode(id);setDraft('');setError('')}} style={[s.tab,mode===id&&s.active]}><Text style={[s.tabText,mode===id&&{color:'#FFFFFF'}]}>{label}</Text></TouchableOpacity>)}</View>
 {mode==='family'&&<View style={s.selector}><TouchableOpacity accessibilityRole="button" accessibilityLabel="选择要了解的家人" onPress={()=>setChoosing(v=>!v)}><Text style={s.person}>{relative?.name||'还没有家人'}　⌄</Text></TouchableOpacity>{choosing&&<ScrollView horizontal contentContainerStyle={{gap:10,paddingTop:12}}>{members.map(p=><TouchableOpacity key={p.id} onPress={()=>{setSelected(p.id);setChoosing(false);setQa([])}} style={s.chip}><Text>{p.name}</Text></TouchableOpacity>)}</ScrollView>}</View>}
 <ScrollView ref={scroller} style={{flex:1}} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scroller.current?.scrollToEnd({animated:true})}><Text style={s.context}>{mode==='self'?'从你愿意说的那一段聊起':'只查看当前家庭可见的资料'}</Text>
 {mode==='self'?<>{data.messages.map(m=><View key={m.id}><View style={s.botRow}><XiaojiaArtwork width={32}/><View style={s.bubble}><Text style={s.body}>{m.question}</Text></View></View><View style={s.userRow}><Text style={s.userBubble}>{m.text}</Text></View></View>)}<View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.body}>{!loaded?'正在读取记录…':question?.text||'今天有什么想说的？一件小事，也可以慢慢聊。'}</Text></View></View>{loaded&&question&&<><View style={s.chips}>{question.options.filter(([id])=>!['skip','unsure'].includes(id)).slice(0,3).map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={'回答'+label} disabled={busy} onPress={()=>send(label)} style={s.chip}><Text style={s.chipText}>{label}</Text></TouchableOpacity>)}</View><View style={s.chips}>{['换个话题','记不清'].map(label=><TouchableOpacity key={label} disabled={busy} onPress={skip} style={s.secondary}><Text style={s.muted}>{label}</Text></TouchableOpacity>)}</View></>}{!!data.messages.length&&<Text style={s.note}>回答已保存在本机 · 尚未分享给家人</Text>}</>:<>{qa.map(m=><View key={m.id}><View style={s.userRow}><Text style={s.userBubble}>{m.question}</Text></View><View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.source}>资料记录</Text><Text style={s.body}>{m.answer}</Text></View></View></View>)}{!qa.length&&<View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.body}>想了解{relative?.name||'哪位家人'}的什么事？</Text></View></View>}</>}
 <Text style={s.note}>测试版：可保存文字回答；智能追问、语音和照片问答尚未接通。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</ScrollView>
 <View style={s.composer}><TextInput accessibilityLabel="给小家的消息" value={draft} onChangeText={setDraft} placeholder={mode==='self'?'想说什么都可以':'问问关于'+(relative?.name||'家人')+'的事'} style={s.input} multiline/><TouchableOpacity accessibilityRole="button" accessibilityLabel="发送给小家" disabled={busy||!loaded||!draft.trim()} onPress={()=>send()} style={[s.send,(busy||!loaded||!draft.trim())&&{opacity:.4}]}><Text style={{color:'#FFFFFF'}}>{busy?'保存中':'发送'}</Text></TouchableOpacity></View></KeyboardAvoidingView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#FFFFFF',maxWidth:600,width:'100%',alignSelf:'center'},header:{height:65,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},back:{position:'absolute',left:16,padding:8},backText:{fontSize:34,color:'#172236'},title:{fontSize:22,fontWeight:'600',color:'#172236'},tabs:{flexDirection:'row',backgroundColor:'#F5F7FA',borderRadius:25,marginHorizontal:20,padding:3},tab:{flex:1,paddingVertical:11,borderRadius:23,alignItems:'center'},active:{backgroundColor:'#347EF0'},tabText:{fontSize:15,color:'#172236'},selector:{marginTop:16,marginHorizontal:30,padding:12,backgroundColor:'#F6F8FB',borderRadius:18},person:{textAlign:'center',fontSize:18,fontWeight:'600'},messages:{padding:20,gap:16,paddingBottom:24},context:{fontSize:13,color:'#788596',textAlign:'center',marginVertical:8},botRow:{flexDirection:'row',alignItems:'flex-start',gap:10,marginVertical:10},bubble:{backgroundColor:'#F4F6F9',padding:16,borderRadius:20,flex:1},body:{fontSize:17,lineHeight:27,color:'#172236'},userRow:{alignItems:'flex-end',marginVertical:12},userBubble:{backgroundColor:'#347EF0',borderRadius:20,padding:15,color:'#FFFFFF',fontSize:17,lineHeight:26,maxWidth:'85%'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginLeft:44},chip:{paddingHorizontal:14,paddingVertical:11,borderWidth:1,borderColor:'#BBD3F5',borderRadius:17},chipText:{fontSize:15,color:'#2876DD'},secondary:{padding:10,backgroundColor:'#F6F8FB',borderRadius:17},muted:{fontSize:14,color:'#788596'},note:{fontSize:12,lineHeight:20,color:'#788596',textAlign:'center'},source:{fontSize:13,color:'#347EF0',marginBottom:8},composer:{flexDirection:'row',gap:8,padding:14,borderTopWidth:1,borderColor:'#EEF1F5',alignItems:'center'},input:{flex:1,minHeight:46,maxHeight:130,backgroundColor:'#F5F7FA',borderRadius:18,padding:12,fontSize:16,color:'#172236'},send:{backgroundColor:'#347EF0',padding:13,borderRadius:16},error:{color:'#B84C45',fontSize:14,lineHeight:22}});
