import React,{useEffect,useState,useRef} from 'react';
import {View,Text,TouchableOpacity,ScrollView,TextInput,StyleSheet,KeyboardAvoidingView,Platform} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import XiaojiaArtwork from './XiaojiaArtwork';
import {interviewQuestions} from './lifeInterview';
const key='jia-xiaojia-conversations-v1';
export default function XiaojiaChatScreen({family,onBack,bottomInset=0,compact=false,tailSide="right"}){
 const [mode,setMode]=useState('self'),[data,setData]=useState({messages:[],answered:[],skipped:[]}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[draft,setDraft]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState(null),[qa,setQa]=useState([]),[choosing,setChoosing]=useState(false);
 const [compactAnswered,setCompactAnswered]=useState(false);
 const [compactWidth,setCompactWidth]=useState(236);
 const lock=useRef(false),scroller=useRef();
 const members=family?.members||[],relative=members.find(p=>p.id===selected)||members.find(p=>p.id!=='me')||members[0];
 const welcomeQuestions=[
 {id:'welcome_childhood_play',bubbleText:'小时候：在家玩，还是出去玩？',text:'小时候，你爱在家玩还是出去玩？',options:[['home','在家里玩'],['outside','跑出去玩']]},
 {id:'welcome_home_memory',bubbleText:'童年的家：先想到饭，还是人？',text:'想起童年的家，你先想到一顿饭还是一个人？',options:[['meal','一顿饭'],['person','一个人']]},
 {id:'welcome_family_time',bubbleText:'和家人相聚：吃饭，还是散步？',text:'和家人多待一会儿，你想吃饭还是散步？',options:[['meal','一起吃饭'],['walk','出去走走']]},
 {id:'welcome_family_talk',bubbleText:'聊家常：往事，还是近况？',text:'和家人聊天，你爱听往事还是聊近况？',options:[['past','过去的故事'],['present','现在的生活']]},
 {id:'welcome_care',bubbleText:'家人难过：陪伴，还是安慰？',text:'家人难过时，你会陪在身边还是开口安慰？',options:[['company','陪在身边'],['words','开口安慰']]},
 {id:'welcome_decisions',bubbleText:'年轻时：听建议，还是自己决定？',text:'年轻时做决定，你听家人建议还是自己拿主意？',options:[['family','听家人的建议'],['self','自己拿主意']]}
 ];
 const activeQuestions=compact?welcomeQuestions:interviewQuestions;
 const question=activeQuestions.find(q=>!data.answered.includes(q.id)&&!data.skipped.includes(q.id));
 useEffect(()=>{let active=true;AsyncStorage.getItem(key).then(raw=>{if(!active)return;if(raw){const p=JSON.parse(raw);if(Array.isArray(p.messages)&&Array.isArray(p.answered))setData({messages:p.messages.filter(m=>m&&typeof m.text==='string'&&typeof m.question==='string'),answered:p.answered.filter(x=>typeof x==='string'),skipped:Array.isArray(p.skipped)?p.skipped.filter(x=>typeof x==='string'):[]})}setLoaded(true)}).catch(()=>{if(active){setError('聊天记录读取失败，请退出后重试。')}});return()=>{active=false}},[]);
 async function persist(next){await AsyncStorage.setItem(key,JSON.stringify(next));setData(next)}
 async function send(text=draft){if(!text.trim()||lock.current||!loaded)return;lock.current=true;setBusy(true);setError('');try{if(mode==='self'){const next={...data,messages:[...data.messages,{id:Date.now(),question:question?.text||'今天有什么想聊的事？',questionId:question?.id||null,text:text.trim(),source:'self',createdAt:new Date().toISOString()}],answered:question?[...data.answered,question.id]:data.answered};await persist(next);setDraft('');if(compact)setCompactAnswered(true)}else{const p=relative;if(!p)throw Error('没有可查看的家人');let answer;if(/几|多少/.test(text)&&/人|口/.test(text))answer=`当前家庭空间登记了 ${members.length} 位家人：${members.map(x=>x.name).join('、')}。这是登记成员，并不代表现实中全部家庭人口。`;else if(/生日|出生/.test(text))answer=p.birthday?`${p.name}的资料中，生日是 ${p.birthday}。`:'这位家人的资料里还没有生日记录。';else answer=`目前可查看${p.name}的基本资料；尚未接通 AI，暂时不能分析这段经历。`;setQa(v=>[...v,{id:Date.now(),question:text.trim(),answer}]);setDraft('')}}catch{setError('未保存成功，输入仍保留，请重试。')}finally{lock.current=false;setBusy(false)}}
 async function skip(){setCompactAnswered(false);if(!question||lock.current)return;lock.current=true;setBusy(true);try{await persist({...data,skipped:[...data.skipped,question.id]})}catch{setError('未能更换问题，请重试。')}finally{lock.current=false;setBusy(false)}}
 if(compact)return <View onLayout={e=>setCompactWidth(e.nativeEvent.layout.width)} style={{width:'100%'}}><View style={s.cartoonBubble}><View pointerEvents="none" style={{position:'absolute',left:0,top:(76-compactWidth)/2,width:compactWidth,height:compactWidth,borderRadius:compactWidth/2,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#A5CAF0',transform:[{scaleY:76/compactWidth}]}}/><Text style={[s.body,{fontSize:15,lineHeight:21,textAlign:'center',maxWidth:190}]}>{!loaded?'让我想想，今天和你聊些什么…':compactAnswered?'记下了，谢谢你。再聊一题吗？':question?(question.bubbleText||question.text).replace('：','：\n'):'这些问题已经聊过了。你随时可以在小家里讲讲新的经历。'}</Text><View pointerEvents="none" style={[s.cartoonTail,tailSide==="left"&&{right:undefined,left:30}]}/></View>
 <View style={{paddingTop:8,paddingHorizontal:3,gap:4}}>{loaded&&!compactAnswered&&question&&<View style={{flexDirection:'row',flexWrap:'wrap',gap:6,justifyContent:'center'}}>{question.options.filter(([id])=>!['unsure','skip'].includes(id)).map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={'欢迎问答选择'+label} disabled={busy} onPress={()=>send(label)} style={[s.chip,{paddingHorizontal:10,paddingVertical:7,backgroundColor:'#FFFFFF'}]}><Text style={[s.chipText,{fontSize:12}]}>{label}</Text></TouchableOpacity>)}</View>}<View style={{flexDirection:'row',gap:12,justifyContent:'center'}}>{loaded&&question&&<TouchableOpacity accessibilityRole="button" accessibilityLabel="下一题" disabled={busy} onPress={compactAnswered?()=>setCompactAnswered(false):skip} style={s.bubbleAction}><Text style={[s.chipText,{fontSize:12}]}>下一题</Text></TouchableOpacity>}<TouchableOpacity accessibilityRole="button" accessibilityLabel="关闭欢迎问答" onPress={onBack} style={s.bubbleAction}><Text style={[s.muted,{fontSize:12}]}>关闭</Text></TouchableOpacity></View></View>{!!error&&<Text accessibilityRole="alert" style={[s.error,{backgroundColor:'#FFFFFF',padding:10,borderRadius:12}]}>{error}</Text>}</View>;
 return <KeyboardAvoidingView style={[s.root,{paddingBottom:bottomInset}]} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><TouchableOpacity accessibilityRole="button" accessibilityLabel="返回首页" onPress={onBack} style={s.back}><Text style={s.backText}>‹</Text></TouchableOpacity><XiaojiaArtwork width={35}/><Text style={s.title}>小家</Text></View><View style={s.tabs}>{[['self','聊聊我的人生'],['family','了解家人']].map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={label} onPress={()=>{setMode(id);setDraft('');setError('')}} style={[s.tab,mode===id&&s.active]}><Text style={[s.tabText,mode===id&&{color:'#FFFFFF'}]}>{label}</Text></TouchableOpacity>)}</View>
 {mode==='family'&&<View style={s.selector}><TouchableOpacity accessibilityRole="button" accessibilityLabel="选择要了解的家人" onPress={()=>setChoosing(v=>!v)}><Text style={s.person}>{relative?.name||'还没有家人'}　⌄</Text></TouchableOpacity>{choosing&&<ScrollView horizontal contentContainerStyle={{gap:10,paddingTop:12}}>{members.map(p=><TouchableOpacity key={p.id} onPress={()=>{setSelected(p.id);setChoosing(false);setQa([])}} style={s.chip}><Text>{p.name}</Text></TouchableOpacity>)}</ScrollView>}</View>}
 <ScrollView ref={scroller} style={{flex:1}} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scroller.current?.scrollToEnd({animated:true})}><Text style={s.context}>{mode==='self'?'从你愿意说的那一段聊起':'只查看当前家庭可见的资料'}</Text>
 {mode==='self'?<>{data.messages.map(m=><View key={m.id}><View style={s.botRow}><XiaojiaArtwork width={32}/><View style={s.bubble}><Text style={s.body}>{m.question}</Text></View></View><View style={s.userRow}><Text style={s.userBubble}>{m.text}</Text></View></View>)}<View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.body}>{!loaded?'正在读取记录…':question?.text||'今天有什么想说的？一件小事，也可以慢慢聊。'}</Text></View></View>{loaded&&question&&<><View style={s.chips}>{question.options.filter(([id])=>!['skip','unsure'].includes(id)).slice(0,3).map(([id,label])=><TouchableOpacity key={id} accessibilityRole="button" accessibilityLabel={'回答'+label} disabled={busy} onPress={()=>send(label)} style={s.chip}><Text style={s.chipText}>{label}</Text></TouchableOpacity>)}</View><View style={s.chips}>{['换个话题','记不清'].map(label=><TouchableOpacity key={label} disabled={busy} onPress={skip} style={s.secondary}><Text style={s.muted}>{label}</Text></TouchableOpacity>)}</View></>}{!!data.messages.length&&<Text style={s.note}>回答已保存在本机 · 尚未分享给家人</Text>}</>:<>{qa.map(m=><View key={m.id}><View style={s.userRow}><Text style={s.userBubble}>{m.question}</Text></View><View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.source}>资料记录</Text><Text style={s.body}>{m.answer}</Text></View></View></View>)}{!qa.length&&<View style={s.botRow}><XiaojiaArtwork width={36}/><View style={s.bubble}><Text style={s.body}>想了解{relative?.name||'哪位家人'}的什么事？</Text></View></View>}</>}
 <Text style={s.note}>测试版：可保存文字回答；智能追问、语音和照片问答尚未接通。</Text>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}</ScrollView>
 <View style={s.composer}><TextInput accessibilityLabel="给小家的消息" value={draft} onChangeText={setDraft} placeholder={mode==='self'?'想说什么都可以':'问问关于'+(relative?.name||'家人')+'的事'} style={s.input} multiline/><TouchableOpacity accessibilityRole="button" accessibilityLabel="发送给小家" disabled={busy||!loaded||!draft.trim()} onPress={()=>send()} style={[s.send,(busy||!loaded||!draft.trim())&&{opacity:.4}]}><Text style={{color:'#FFFFFF'}}>{busy?'保存中':'发送'}</Text></TouchableOpacity></View></KeyboardAvoidingView>
}
const s=StyleSheet.create({cartoonBubble:{height:76,paddingHorizontal:20,alignItems:'center',justifyContent:'center'},cartoonTail:{position:'absolute',right:26,bottom:-5,width:12,height:12,backgroundColor:'#FFFFFF',transform:[{rotate:'45deg'}],borderRightWidth:1,borderBottomWidth:1,borderColor:'#A5CAF0'},bubbleAction:{paddingHorizontal:12,paddingVertical:7,minHeight:30,borderRadius:18,backgroundColor:'#FFFFFF'},root:{flex:1,backgroundColor:'#FFFFFF',maxWidth:600,width:'100%',alignSelf:'center'},header:{height:65,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:10},back:{position:'absolute',left:16,padding:8},backText:{fontSize:34,color:'#172236'},title:{fontSize:22,fontWeight:'600',color:'#172236'},tabs:{flexDirection:'row',backgroundColor:'#F5F7FA',borderRadius:25,marginHorizontal:20,padding:3},tab:{flex:1,paddingVertical:11,borderRadius:23,alignItems:'center'},active:{backgroundColor:'#347EF0'},tabText:{fontSize:15,color:'#172236'},selector:{marginTop:16,marginHorizontal:30,padding:12,backgroundColor:'#F6F8FB',borderRadius:18},person:{textAlign:'center',fontSize:18,fontWeight:'600'},messages:{padding:20,gap:16,paddingBottom:24},context:{fontSize:13,color:'#788596',textAlign:'center',marginVertical:8},botRow:{flexDirection:'row',alignItems:'flex-start',gap:10,marginVertical:10},bubble:{backgroundColor:'#F4F6F9',padding:16,borderRadius:20,flex:1},body:{fontSize:17,lineHeight:27,color:'#172236'},userRow:{alignItems:'flex-end',marginVertical:12},userBubble:{backgroundColor:'#347EF0',borderRadius:20,padding:15,color:'#FFFFFF',fontSize:17,lineHeight:26,maxWidth:'85%'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginLeft:44},chip:{paddingHorizontal:14,paddingVertical:11,borderWidth:1,borderColor:'#BBD3F5',borderRadius:17},chipText:{fontSize:15,color:'#2876DD'},secondary:{padding:10,backgroundColor:'#F6F8FB',borderRadius:17},muted:{fontSize:14,color:'#788596'},note:{fontSize:12,lineHeight:20,color:'#788596',textAlign:'center'},source:{fontSize:13,color:'#347EF0',marginBottom:8},composer:{flexDirection:'row',gap:8,padding:14,borderTopWidth:1,borderColor:'#EEF1F5',alignItems:'center'},input:{flex:1,minHeight:46,maxHeight:130,backgroundColor:'#F5F7FA',borderRadius:18,padding:12,fontSize:16,color:'#172236'},send:{backgroundColor:'#347EF0',padding:13,borderRadius:16},error:{color:'#B84C45',fontSize:14,lineHeight:22}});
